In [1]:
import json
import os
import pandas as pd 
import numpy as np 
from tqdm import tqdm
import torch
from torch import nn, optim
import torch.nn.functional as F
from torchvision import models
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from transformers import VideoMAEForVideoClassification
from sklearn import metrics
from matplotlib import pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
import seaborn as sns
import cv2
from PIL import Image

In [8]:
# Extract and process captions

ROOT = r"C:\Users\Keelan24\Documents\My Projects\MSC Final"
JSON_PATHS = os.path.join(ROOT,"Capdata","All the annotation","All the annotation")
IMAGE_FOLDERS =  os.path.join(ROOT,"Capdata","UCF crime Extrated frame Dataset","UCF crime Extrated frame Dataset")
os.listdir(JSON_PATHS)

['Abuse.json',
 'Arson.json',
 'Assault.json',
 'Burglary.json',
 'Explosion.json',
 'Fighting.json',
 'Normal.json',
 'Normal_Videos part1.json',
 'Normal_Videos part2.json',
 'Normal_Videos part3.json',
 'Normal_Videos part4.json',
 'Robbery.json',
 'Shooting.json',
 'Shoplifting.json',
 'Stealing.json',
 'Vandalism.json']

In [21]:
def extract_json(json_path, JSON_PATHS = JSON_PATHS):
    p = os.path.join(JSON_PATHS, json_path)
    with open(p, 'r') as f:
        data = json.load(f)
    df = pd.DataFrame.from_dict(data, orient='index')
    df.index.name = 'video_id'

    return df


for json_file in os.listdir(JSON_PATHS):
    display(extract_json(json_file))

,duration,timestamps,sentences
video_id,,,
Abuse001_x264,91.00,"[[0.0, 5.3], [7.0, 8.5], [7.2, 8.5], [8.2, 8.9...","[A woman with short hair, slightly fat, wearin..."
Abuse002_x264,28.83,"[[0.0, 2.3], [0.0, 2.3], [2.3, 3.2], [2.3, 3.3...","[At an intersection with smooth traffic, the g..."
Abuse003_x264,123.32,"[[0.0, 23.1], [23.1, 30.7], [30.7, 31.9], [31....",[A woman in black short-sleeves pushed an old ...
Abuse004_x264,559.82,"[[0.0, 9.6], [9.9, 15.2], [16.6, 17.8], [17.6,...",[Two bald policemen in black uniforms held the...
Abuse005_x264,31.65,"[[0.0, 3.3], [0.0, 3.3], [0.0, 3.3], [3.5, 7.5...",[The prison guard wearing black trousers and g...
Abuse006_x264,146.00,"[[3.0, 7.6], [3.0, 7.6], [7.0, 11.2], [11.5, 1...","[A police car drove into a grassy field, A man..."
Abuse007_x264,38.36,"[[0.1, 3.5], [0.1, 3.5], [3.3, 4.5], [4.9, 6.5...",[A man wearing black short-sleeved green short...
Abuse008_x264,280.29,"[[0.0, 10.3], [11.4, 28.0], [27.4, 39.2], [40....",[A female police officer in black uniform bent...
Abuse009_x264,33.51,"[[0.0, 7.2], [8.9, 15.2], [14.9, 16.0], [16.3,...","[At night, there were a bunch of men standing ..."
Abuse010_x264,37.89,"[[0.0, 2.3], [3.2, 5.1], [6.0, 11.9], [6.0, 14...",[There are two silver cars driving opposite ea...
Abuse011_x264,121.56,"[[9.8, 13.0], [14.3, 17.8], [17.8, 19.0], [19....",[A man faced a house at the corner of the stai...
Abuse012_x264,171.05,"[[0.0, 9.6], [9.6, 17.7], [18.9, 54.8], [55.9,...",[The five babies in the room were each lying i...
Abuse013_x264,162.35,"[[0.0, 6.7], [8.0, 12.1], [12.2, 14.4], [18.0,...",[ Kindergarten children stood in three rows in...
Abuse014_x264,86.33,"[[0.0, 20.2], [21.7, 30.3], [24.0, 26.1], [26....","[ There are three cars on the road, two green ..."
Abuse015_x264,262.53,"[[36.4, 40.1], [40.3, 43.1], [42.9, 50.2], [51...",[There are three men wearing black clothes and...
Abuse016_x264,46.94,"[[3.0, 7.3], [7.9, 11.9], [12.0, 16.4], [17.0,...","[A yellow dog ran from the yard to the gate, a..."
Abuse017_x264,64.02,"[[3.4, 10.3], [7.4, 12.5], [16.9, 21.2], [21.3...",[A woman in a white top pushed the child in or...
Abuse018_x264,81.11,"[[2.2, 10.3], [11.9, 20.3], [21.5, 40.4], [41....",[ Vehicles were coming and going on the street...
Abuse019_x264,131.50,"[[0.1, 6.1], [6.1, 15.9], [16.3, 20.6], [22.6,...",[Two women were communicating next to the bed....
Abuse020_x264,103.49,"[[0.9, 13.9], [19.7, 40.0], [40.5, 52.8], [53....",[A man in a white shirt hit a woman sitting on...
Abuse021_x264,63.79,"[[1.3, 7.6], [8.3, 12.0], [15.6, 18.0], [18.4,...",[ Five children eat around a semi-circular tab...
Abuse022_x264,94.58,"[[0.0, 6.0], [5.8, 9.6], [9.8, 11.5], [11.5, 1...",[A man in white short-sleeves is pushing a whe...
Abuse023_x264,33.09,"[[0.0, 3.4], [4.4, 5.2], [6.3, 8.3], [9.4, 18.2]]",[The woman in a blue top is watching the situa...
Abuse024_x264,34.09,"[[2.1, 11.6], [15.5, 22.1], [22.5, 24.2], [24....",[A man was pushing a shopping cart in front of...
Abuse025_x264,67.78,"[[0.3, 7.2], [7.3, 10.2], [11.3, 16.3], [16.4,...",[There was a woman wearing white and blue stri...
Abuse026_x264,66.20,"[[0.0, 10.6], [10.9, 20.4], [20.7, 30.5], [30....",[A powerful and tall man threw a woman to the ...
Abuse027_x264,145.73,"[[0.0, 9.3], [10.3, 14.3], [15.8, 31.3], [38.4...",[A baby was rocking on a cradle made of blue c...
Abuse028_x264,47.13,"[[0.7, 6.7], [6.7, 14.7], [15.3, 22.4], [26.7,...",[A gray-coated postman walked to the mailbox a...
Abuse029_x264,10.06,"[[1.6, 3.3], [4.3, 5.1], [6.1, 8.9], [9.1, 10.0]]",[A man in a red shirt and brown trousers walke...
Abuse030_x264,51.52,"[[1.3, 5.5], [6.4, 10.8], [11.3, 13.0], [14.3,...",[A black puppy walked out from in front of the...
Abuse031_x264,148.10,"[[4.3, 10.3], [11.2, 16.3], [17.3, 20.6], [21....",[There is a red car on the roadside. A middle-...
Abuse032_x264,158.36,"[[19.4, 23.2], [24.4, 34.3], [48.2, 61.9], [62...",[There was a woman in floral clothes squatting...
Abuse033_x264,94.41,"[[0.2, 5.4], [6.3, 10.5], [11.2, 20.3], [21.5,...",[There are two people in a smaller room. One i...
Abuse034_x264,52.13,"[[0.0, 5.4], [6.4, 12.3], [12.3, 17.9], [19.5,...","[Vehicles are driving normally on the road, a ..."
Abuse035_x264,88.40,"[[0.3, 3.2], [3.2, 5.3], [5.6, 15.3], [15.2, 2...","[In a kindergarten, a short-haired kindergarte..."
Abuse036_x264,156.81,"[[0.0, 10.1], [11.2, 15.3], [16.4, 72.9], [73....","[ started to introduce herself, and a woman in..."
Abuse037_x264,59.88,"[[1.2, 8.2], [8.4, 25.3], [25.3, 48.5], [48.5,...",[A white car with double flashes slowly appear...
Abuse038_x264,29.72,"[[0.3, 10.4], [11.5, 17.2], [17.2, 22.9], [14....",[ Several adults were talking on the side of t...
Abuse039_x264,471.52,"[[0.0, 7.5], [7.5, 12.6], [12.6, 39.3], [19.5,...",[A yellow-haired woman in black clothes walked...
Abuse040_x264,113.82,"[[9.2, 23.4], [26.6, 40.3], [40.3, 44.4], [46....",[A woman in a blue top walked into the room ne...
Abuse041_x264,46.19,"[[0.0, 5.3], [6.3, 15.6], [16.9, 20.2], [24.3,...",[A woman wearing pink clothes is holding a chi...
Abuse042_x264,949.28,"[[6.1, 33.8], [30.8, 46.2], [49.8, 54.6], [55....",[A woman in a pink skirt is sitting on the gro...
Abuse043_x264,129.08,"[[3.4, 7.4], [7.3, 15.4], [15.5, 22.2], [22.9,...",[The female nanny had a very bad attitude towa...
Abuse044_x264,131.43,"[[0.1, 1.4], [1.4, 6.1], [6.1, 15.9], [16.3, 2...",[Two women were communicating next to the bed....
Abuse045_x264,169.62,"[[0.0, 12.0], [12.5, 19.7], [19.9, 26.7], [27....",[The woman lying on the sofa kicked the old ma...
Abuse046_x264,38.75,"[[4.4, 10.4], [12.4, 14.7], [15.7, 20.2], [20....","[A woman kicked a puppy in the yard, and anoth..."
Abuse047_x264,52.25,"[[1.9, 8.9], [10.1, 13.8], [15.8, 23.4], [25.3...","[In a room, there were many children taking a ..."
Abuse048_x264,114.03,"[[1.2, 2.3], [3.3, 5.4], [6.4, 16.5], [17.9, 2...",[A woman wearing a white top slapped an old ma...
Abuse049_x264,71.33,"[[5.0, 16.7], [18.3, 24.0], [25.6, 38.6], [40....",[A man helped a staggering old man sit on the ...
Abuse050_x264,162.07,"[[0.7, 5.3], [5.1, 8.3], [11.2, 16.6], [16.9, ...","[On a bus, a boy wearing a white and blue vest..."

,duration,timestamps,sentences
video_id,,,
Arson001_x264,139.60,"[[19.3, 21.4], [32.5, 36.2], [36.1, 44.0], [46...",[The door of a white car parked in front of th...
Arson002_x264,148.04,"[[0.0, 6.1], [14.5, 29.9], [30.9, 37.8], [47.8...",[A man in green clothes and a hat came to the ...
Arson003_x264,133.80,"[[0.1, 17.5], [30.3, 49.1], [49.6, 90.6], [94....",[A man in white clothes ran and poured gasolin...
Arson005_x264,39.19,"[[0.0, 4.1], [4.3, 8.2], [22.9, 38.6]]",[A man in black appeared with a gasoline bucke...
Arson006_x264,93.90,"[[6.3, 18.4], [20.2, 58.4], [73.6, 83.5]]",[A man with a turban on his head entered the h...
Arson007_x264,208.45,"[[16.1, 26.5], [29.7, 37.6], [41.7, 104.9], [1...",[A man carrying a bag of things in one hand wa...
Arson008_x264,40.79,"[[0.4, 6.4], [12.3, 17.0], [17.2, 20.4], [20.1...",[A man poured gasoline on the table with a buc...
Arson009_x264,24.94,"[[0.0, 8.3], [8.2, 10.0], [11.2, 22.0]]",[A man in a hat and white clothes is wandering...
Arson010_x264,105.30,"[[8.1, 13.5], [20.4, 30.3], [30.1, 32.0], [33....",[A motorcycle carrying two people arrived at t...
Arson011_x264,42.24,"[[2.2, 9.6]]",[A man entered the elevator and kept lighting ...
Arson012_x264,29.88,"[[1.9, 5.2], [10.7, 12.6], [19.7, 20.3]]",[A man bent down in the parking lot and lit th...
Arson013_x264,212.74,"[[19.9, 41.2], [50.3, 56.1], [68.0, 76.0], [10...",[A man in purple walked to the door of the hou...
Arson014_x264,87.99,"[[8.5, 18.1], [21.3, 33.9], [33.5, 39.8], [40....","[A man came to a van parked on the roadside, T..."
Arson015_x264,341.07,"[[25.3, 32.2], [30.9, 40.1], [41.8, 50.3], [47...",[ Three people wearing hoods came from the sta...
Arson016_x264,59.87,"[[1.6, 12.6], [15.7, 20.0], [20.0, 25.7], [30....",[A man sitting in the last row of the bus took...
Arson017_x264,46.17,"[[4.4, 9.9], [11.5, 17.1], [21.3, 28.9], [31.5...",[A man walks from the far left to the far righ...
Arson018_x264,28.10,"[[2.7, 12.6], [13.4, 17.9], [19.5, 25.8]]",[A man in black came to a car and sprinkled ga...
Arson019_x264,4218.50,"[[400.1, 403.5], [412.7, 422.4], [478.7, 482.1...",[A man quickly came to a black car parked on t...
Arson020_x264,80.95,"[[5.0, 10.6], [38.0, 45.4], [46.6, 54.0], [54....",[A car drove to the side of the road and stopp...
Arson021_x264,48.07,"[[4.3, 10.5], [10.1, 26.9], [30.8, 36.5], [36....",[A man in black rode a bicycle to the door of ...
Arson022_x264,288.02,"[[1.6, 7.4], [15.5, 20.9], [21.1, 29.9], [30.0...","[A man in black entered a house from the gate,..."
Arson023_x264,45.62,"[[1.7, 17.9], [17.8, 36.8], [40.9, 45.3]]","[A man in gray clothes came to the white car,,..."
Arson024_x264,112.25,"[[41.4, 43.5], [48.5, 50.7], [70.2, 110.6]]",[A man in white poured gasoline on a man lying...
Arson025_x264,176.10,"[[0.9, 9.8], [25.1, 34.3], [34.0, 45.9], [70.2...",[A man rode a bicycle to a black car parked on...
Arson026_x264,196.63,"[[7.8, 17.3], [18.3, 28.0], [49.2, 56.7], [88....",[A man in white clothes in a store pushed a st...
Arson027_x264,90.00,"[[1.3, 28.3], [0.7, 28.9], [29.3, 40.6], [55.4...",[A man in a white vest came to the table in th...
Arson028_x264,80.30,"[[3.2, 7.1], [14.0, 20.9], [29.8, 30.3], [47.3...",[A car stopped in front of the gate of a house...
Arson029_x264,44.97,"[[0.7, 9.5], [10.6, 27.7], [31.7, 39.0]]",[A man in white clothes is squatting in the la...
Arson030_x264,168.43,"[[20.8, 26.0], [50.0, 52.5], [103.9, 109.3], [...",[ Two people set fire to a tree next to the ro...
Arson031_x264,96.13,"[[1.5, 35.2], [35.1, 40.9], [45.1, 50.5], [58....",[Two people dressed in white rushed into the h...
Arson032_x264,92.72,"[[2.3, 20.6], [20.2, 37.1], [45.0, 50.8], [55....",[Two people threw burning torches at a house a...
Arson034_x264,79.60,"[[1.5, 20.2], [1.5, 20.2], [20.2, 30.6], [31.2...",[A man in white clothes kept walking backwards...
Arson035_x264,47.95,"[[10.9, 18.9], [18.0, 24.4], [26.5, 42.2]]",[A man in a hat came to a van and poured gasol...
Arson036_x264,56.63,"[[2.1, 26.5], [28.6, 40.7], [48.1, 52.5], [52....",[A black man in white clothes and a hat holdin...
Arson037_x264,26.77,"[[3.2, 5.4], [11.3, 15.0]]",[A man wearing a white hat came to the door of...
Arson038_x264,24.61,"[[1.5, 7.8], [8.8, 11.6], [13.1, 17.8], [18.1,...",[A man ran to the house with a torch and threw...
Arson039_x264,112.53,"[[2.5, 5.5], [8.9, 10.0], [14.4, 25.1]]",[A man in white clothes poured gasoline in fro...
Arson040_x264,94.50,"[[1.6, 10.1], [11.7, 15.1], [25.1, 32.6], [43....",[A man poured gasoline on the wall. The man wa...
Arson041_x264,125.23,"[[2.1, 50.2], [50.4, 56.5], [70.0, 100.4], [11...",[A man in black was wandering in front of the ...
Arson042_x264,195.84,"[[3.5, 55.7], [69.5, 78.7], [100.5, 118.1], [1...","[A person lingered in front of the door, stood..."
Arson044_x264,39.92,"[[3.1, 10.9], [10.4, 35.9], [32.4, 38.9]]",[A man in black set a motorcycle parked on the...
Arson045_x264,125.13,"[[5.3, 15.2], [15.6, 20.7], [20.8, 28.5], [32....",[A man in gray came to the front of a white wa...
Arson046_x264,69.15,"[[2.4, 10.3], [10.0, 27.9], [28.5, 63.5], [64....",[A man in black came to a window of a room on ...
Arson047_x264,48.16,"[[0.8, 7.5], [10.8, 11.1], [14.5, 20.3], [28.6...",[A man in blue pressed the elevator button at ...
Arson048_x264,13.81,"[[0.2, 2.7], [3.7, 5.8]]",[Three black objects in the lower right corner...
Arson049_x264,12.91,"[[0.8, 4.5], [4.4, 6.9], [10.1, 12.9]]",[The two of them kept throwing burning torches...
Arson050_x264,52.77,"[[3.7, 7.1], [5.2, 10.6], [18.0, 24.2], [32.5,...",[Three people broke into the store from the st...

,duration,timestamps,sentences
video_id,,,
Assault001_x264,82.94,"[[4.2, 13.3], [13.4, 22.3], [22.7, 28.5], [28....",[Three men were fighting. Two men knocked the ...
Assault002_x264,84.13,"[[1.4, 5.1], [5.0, 10.0], [11.7, 17.4], [17.4,...",[More than a dozen dark-skinned men filed into...
Assault003_x264,148.10,"[[0.0, 11.2], [11.2, 12.1], [13.1, 18.1], [18....","[Two men stood at the door, About 5 or 6 peop..."
Assault004_x264,107.43,"[[1.9, 24.0], [25.6, 26.2], [26.6, 28.2], [29....",[ There were four men on the roadside. When th...
Assault005_x264,40.57,"[[3.2, 10.7], [12.8, 19.3], [20.2, 25.4], [26....","[Five men walked into a yard, A group of peopl..."
Assault006_x264,269.87,"[[1.6, 20.9], [20.9, 36.9], [36.9, 40.3], [40....",[A black boy wearing a backpack and a white co...
Assault007_x264,65.07,"[[1.7, 7.0], [5.1, 7.0], [10.8, 20.3], [22.8, ...","[In a room with two cash machines, a man was s..."
Assault008_x264,251.20,"[[1.4, 5.7], [5.6, 9.8], [5.6, 9.8], [10.0, 15...",[5 or 6 people outside the hospital stood toge...
Assault009_x264,120.08,"[[1.5, 14.1], [14.7, 21.9], [21.1, 27.4], [33....",[Two men and a woman were drinking water and c...
Assault010_x264,539.36,"[[1.2, 40.3], [33.2, 42.3], [54.1, 220.9], [21...",[In a large room with many beds and multiple l...
Assault011_x264,76.37,"[[13.2, 37.1], [41.5, 48.1], [50.5, 75.3]]",[Three men beat a man with sticks until someon...
Assault012_x264,26.34,"[[1.7, 9.9], [10.2, 12.3], [15.1, 25.9]]","[Two men walking on the road, walking from one..."
Assault013_x264,79.34,"[[1.3, 18.5], [19.0, 26.8], [19.5, 26.0], [41....","[In the restaurant, two women wanted to leave ..."
Assault014_x264,63.61,"[[1.2, 5.1], [5.0, 8.8], [1.8, 8.8], [9.3, 10....",[There is a black car parked on the side of th...
Assault015_x264,49.40,"[[1.8, 10.5], [14.0, 14.7], [14.8, 19.7], [20....","[In the small shop, the shopkeeper stood behin..."
Assault016_x264,220.60,"[[1.8, 4.9], [5.2, 20.5], [27.1, 30.0], [31.5,...",[2 staff members were standing and talking in ...
Assault017_x264,81.67,"[[7.4, 19.9], [20.5, 30.4], [31.2, 35.6], [35....","[A man came to a black car, opened the small d..."
Assault018_x264,12.54,"[[1.0, 3.6], [3.9, 11.2]]",[Two men appeared. The man walking behind punc...
Assault019_x264,84.64,"[[4.1, 27.8], [28.6, 30.0], [31.2, 35.6], [37....","[The window of the shop was broken, and severa..."
Assault020_x264,15.95,"[[2.2, 6.6], [7.3, 10.3], [11.7, 15.3]]",[ Four people were standing together on the ro...
Assault022_x264,84.08,"[[1.2, 18.4], [19.7, 23.3], [24.6, 29.6], [29....","[In the circular parking lot, three men in bla..."
Assault023_x264,33.77,"[[3.8, 30.0], [29.0, 30.0]]","[Four men stood on the roadside talking., Sudd..."
Assault024_x264,14.92,"[[1.4, 6.8], [8.9, 12.3]]",[There was a group of people on the empty fiel...
Assault025_x264,38.85,"[[1.2, 14.4], [14.2, 17.7], [18.0, 20.8], [20....",[A group of people stood on one side of the ro...
Assault026_x264,28.21,"[[7.8, 20.3], [21.5, 26.0]]",[A man wearing a white T-shirt beat a man in b...
Assault027_x264,231.67,"[[1.6, 30.4], [31.5, 39.0], [80.2, 95.9], [115...",[A man enters a small store and talks to the m...
Assault028_x264,87.87,"[[13.7, 20.7], [20.3, 30.3], [30.1, 33.5], [50...",[A man in white walks towards a black car on t...
Assault029_x264,20.35,"[[1.9, 16.2]]",[Two men kicked objects on the ground on the r...
Assault030_x264,58.94,"[[1.1, 7.9], [20.3, 40.0], [50.4, 55.2]]",[Two men entered the elevator one after anothe...
Assault031_x264,25.23,"[[7.9, 20.4]]","[A group of people were beating each other, an..."
Assault032_x264,19.09,"[[1.1, 6.6], [8.6, 18.0]]","[A person was walking on the sidewalk, and a p..."
Assault033_x264,42.66,"[[2.4, 8.5], [20.7, 26.3], [27.7, 39.9], [40.6...",[A girl carrying a backpack entered the elevat...
Assault034_x264,77.35,"[[1.9, 20.4], [20.1, 28.0], [29.3, 33.6], [34....",[Three men were talking at the entrance of the...
Assault035_x264,30.01,"[[1.8, 19.7], [19.2, 22.0], [22.4, 30.0]]",[Two men walked around a gray car beating anot...
Assault036_x264,30.49,"[[1.4, 3.4], [4.8, 29.1]]",[Two men were standing in the middle of the ro...
Assault037_x264,106.98,"[[12.2, 17.8], [20.6, 25.6], [25.8, 80.7]]","[A large group of people gathered at a bar., A..."
Assault038_x264,4.63,"[[1.5, 4.6]]",[A man in white clothes and gray trousers punc...
Assault039_x264,9.83,"[[1.5, 3.3], [4.5, 8.7]]",[An African-American man wearing a red shirt e...
Assault040_x264,126.07,"[[25.1, 35.0], [35.5, 65.7], [70.1, 124.2]]","[ Near the parking lot at night, three men bea..."
Assault041_x264,167.44,"[[1.7, 45.7], [16.3, 80.7], [85.4, 87.4], [90....",[The owner of the small shop was arguing behin...
Assault042_x264,299.83,"[[1.0, 49.3], [50.9, 100.4], [100.2, 119.5], [...","[On the road, a man stopped the person on the ..."
Assault044_x264,25.50,"[[1.9, 16.6], [16.8, 17.9], [1.6, 20.6], [21.7...","[In an open space in front of a glass door, a ..."
Assault047_x264,111.22,"[[1.6, 10.8], [70.7, 80.9], [82.3, 110.6]]",[A group of people ran from the middle of the ...
Assault048_x264,60.06,"[[5.3, 10.7], [10.7, 28.2], [28.9, 33.0], [35....","[ On the side of the traffic jam, a man with c..."
Assault049_x264,44.23,"[[1.8, 9.3], [12.5, 14.3], [15.3, 18.1]]","[Two men, one sitting and one standing, were t..."
Assault050_x264,20.85,"[[1.9, 19.6], [12.3, 20.3]]","[In a small supermarket, a woman in purple kno..."
Assault051_x264,20.04,"[[1.5, 5.1], [7.0, 8.3], [9.3, 18.8]]","[At night, several policemen and two from the ..."
Assault052_x264,26.31,"[[1.8, 9.2], [10.4, 17.2], [18.1, 25.7]]","[At night, a man ran across the road and rushe..."

,duration,timestamps,sentences
video_id,,,
Burglary001_x264,132.38,"[[7.4, 12.6], [12.7, 16.2], [20.3, 35.9], [26....","[A truck backed up quickly, broke through the ..."
Burglary002_x264,102.17,"[[5.0, 10.1], [11.5, 35.5], [23.5, 84.7], [83....",[A man in white entered the room and came to t...
Burglary003_x264,39.10,"[[1.6, 10.5], [10.5, 13.5], [15.5, 17.3], [18....",[A man is rummaging through a large cardboard ...
Burglary004_x264,59.61,"[[1.3, 7.2], [7.3, 9.6], [7.3, 10.6], [9.3, 11...",[A car crashed directly into the glass window ...
Burglary005_x264,258.08,"[[1.7, 13.4], [13.7, 20.4], [20.2, 30.8], [31....",[An African-American man wearing a white T-shi...
Burglary006_x264,297.95,"[[5.2, 10.3], [10.2, 36.3], [123.1, 132.6], [1...",[A man in white climbed into the room from the...
Burglary007_x264,36.17,"[[1.1, 9.7], [1.1, 12.7], [9.1, 11.7], [13.5, ...","[Two men stood in front of the shop,, A white ..."
Burglary008_x264,164.03,"[[8.6, 11.9], [8.6, 10.9], [11.6, 18.7], [47.8...",[Two men were standing next to the glass door ...
Burglary009_x264,85.23,"[[23.6, 26.1], [28.3, 30.8], [28.3, 30.2], [31...",[The two broke into the shop from outside the ...
Burglary010_x264,196.27,"[[0.5, 90.0], [95.5, 100.0], [100.1, 135.9], [...",[There are two cash machines in the corner of ...
Burglary011_x264,65.47,"[[2.1, 5.4], [5.2, 8.9], [9.9, 15.2], [15.4, 1...","[A car reversed and hit the house, The car rev..."
Burglary012_x264,56.60,"[[1.2, 5.8], [5.2, 10.8], [10.1, 25.2], [25.2,...",[Three men pulled down their guns in front of ...
Burglary013_x264,74.47,"[[5.5, 20.8], [10.5, 20.8], [20.9, 29.7], [20....",[ Three men wearing blue coats and blue woolen...
Burglary014_x264,85.83,"[[0.3, 4.3], [4.3, 8.9], [8.6, 16.3], [16.2, 2...",[The rear of a car was close to the door and d...
Burglary015_x264,37.37,"[[1.7, 3.6], [3.8, 7.6], [8.1, 16.6], [8.8, 16...",[More than 10 people wearing clothes of differ...
Burglary016_x264,175.27,"[[1.5, 20.2], [20.7, 26.1], [26.9, 34.0], [26....",[A red car slowly poured into a field filled w...
Burglary017_x264,70.43,"[[1.6, 10.4], [14.4, 16.7], [16.4, 17.7], [18....",[A man walked into the room and jumped on the ...
Burglary018_x264,37.54,"[[3.8, 10.1], [10.8, 18.1], [18.8, 33.3], [33....",[A man in white clothes and a helmet walked fr...
Burglary019_x264,96.47,"[[1.8, 3.1], [3.8, 5.1], [5.2, 10.1], [10.5, 2...",[A man wearing a baseball cap reached in from ...
Burglary020_x264,110.42,"[[10.6, 13.3], [13.0, 18.9], [21.6, 28.9], [34...","[A man in black broke into a small shop., The ..."
Burglary021_x264,51.28,"[[1.9, 7.4], [7.9, 9.1], [9.9, 11.2], [11.2, 1...","[A truck drove backwards, and its rear directl..."
Burglary022_x264,94.73,"[[1.5, 22.3], [23.1, 25.3], [25.1, 28.3], [28....",[The two people appeared at the door and took ...
Burglary023_x264,331.59,"[[1.7, 20.8], [15.7, 18.8], [20.7, 40.3], [40....",[A man was trying to move a bicycle near the d...
Burglary024_x264,120.29,"[[1.2, 14.3], [14.2, 24.2], [21.3, 34.3], [31....",[A shirtless man entered a workstation in an o...
Burglary025_x264,207.17,"[[1.5, 6.5], [11.2, 35.0], [50.6, 57.3], [63.6...",[An African-American man came in from the door...
Burglary026_x264,51.14,"[[1.3, 11.4], [11.1, 16.2], [30.0, 36.2], [36....",[A man wearing a hat and clothes with GAP prin...
Burglary027_x264,103.40,"[[1.1, 6.6], [1.1, 6.6], [1.1, 6.6], [7.4, 10....","[A car broke into the mobile phone store., Two..."
Burglary028_x264,31.84,"[[1.7, 4.9], [4.2, 7.1], [10.0, 15.9], [15.1, ...","[Three men stood in front of the window, actin..."
Burglary029_x264,167.44,"[[1.5, 3.1], [3.5, 10.1], [15.5, 17.1], [20.2,...","[A young white man appears in the room, The ma..."
Burglary030_x264,30.02,"[[10.6, 15.7], [15.6, 19.7], [20.6, 23.7], [23...",[The three of them entered the room and search...
Burglary031_x264,208.61,"[[0.1, 15.1], [15.1, 30.1], [33.2, 61.6], [63....","[A store with lights on and no one, A store wi..."
Burglary032_x264,526.55,"[[17.2, 27.2], [27.2, 47.4], [37.5, 40.6], [40...",[A man wearing a white hooded jacket jumped ou...
Burglary033_x264,42.03,"[[0.0, 4.2], [4.0, 6.2], [6.0, 9.2], [10.0, 12...",[A young white man wearing a black coat with a...
Burglary034_x264,42.61,"[[9.0, 14.1], [14.4, 17.8], [16.4, 17.8], [14....","[Two African-American men wearing T-shirts, sh..."
Burglary035_x264,135.05,"[[1.1, 33.6], [33.1, 43.6], [47.5, 56.2], [56....",[A man wearing a white hoodie and white shorts...
Burglary036_x264,33.47,"[[1.3, 5.8], [5.3, 11.8], [12.4, 22.0], [22.4,...",[A man with a gray woolen hat walked into the ...
Burglary037_x264,64.10,"[[7.2, 14.8], [16.8, 20.9], [21.3, 30.1], [30....",[An African-American man wearing a white coat ...
Burglary038_x264,30.03,"[[1.1, 6.3], [6.1, 8.3], [6.1, 8.3], [9.3, 14....",[A man in white climbed into the room from the...
Burglary039_x264,314.07,"[[5.3, 12.0], [12.0, 20.3], [20.0, 63.3], [65....",[A red car drove up and parked in front of the...
Burglary040_x264,190.11,"[[5.5, 16.5], [16.5, 18.5], [20.2, 24.8], [24....",[A silver-white car made a U-turn from across ...
Burglary041_x264,60.57,"[[0.2, 3.0], [3.2, 13.0], [13.8, 20.2], [23.8,...",[An African-American boy wearing a brown shirt...
Burglary042_x264,141.11,"[[4.1, 8.1], [8.8, 13.1], [14.8, 26.8], [24.8,...",[An African-American man wearing a white short...
Burglary043_x264,18.01,"[[7.3, 12.8], [12.3, 14.8], [14.3, 16.8], [16....",[An African-American man wearing a white hoode...
Burglary044_x264,229.10,"[[1.7, 8.9], [8.7, 15.9], [15.7, 23.9], [26.7,...",[A Caucasian man wearing white clothes and pan...
Burglary045_x264,365.38,"[[1.3, 55.3], [20.3, 35.3], [37.9, 54.3], [42....",[ Two men cooperated in front of the glass doo...
Burglary046_x264,76.40,"[[1.2, 8.9], [9.3, 17.0], [17.3, 28.0], [28.3,...",[A man wearing a white shirt and gray suit pus...
Burglary047_x264,92.04,"[[8.8, 24.4], [24.9, 27.0], [28.7, 44.7], [40....",[A man punched the glass door of his office an...
Burglary048_x264,55.03,"[[5.1, 10.5], [10.1, 15.5], [15.1, 20.5], [21....","[A tall white man wearing a thick jacket, blac..."
Burglary049_x264,307.32,"[[1.3, 7.8], [8.3, 13.8], [13.1, 21.9], [22.6,...",[A man wearing a white hoodie (dark sleeves) a...
Burglary050_x264,38.17,"[[1.4, 4.3], [4.4, 7.3], [7.4, 10.3], [11.6, 1...",[A dark-skinned man wearing a white helmet and...

,duration,timestamps,sentences
video_id,,,
Explosion001_x264,21.72,"[[3.7, 13.6]]","[After a burst of light, dust, soil and rocks ..."
Explosion002_x264,133.77,"[[12.5, 18], [12.5, 23.9], [22.6, 32.7], [49.5...",[A man in blue is walking with something in hi...
Explosion003_x264,19.20,"[[0, 3.1], [3, 6.2], [6.3, 7], [7, 18.9]]","[Many cars are driving on the road., An explos..."
Explosion004_x264,63.53,"[[0, 2.1], [2, 6.2], [3.1, 17.1], [18.7, 29.4]...",[Two people wearing firefighting gear stood ou...
Explosion005_x264,23.11,"[[0, 8], [1, 13], [7.6, 11.8], [11.6, 23.1], [...",[There are many vehicles driving on the two-wa...
Explosion006_x264,64.04,"[[0, 64], [0, 4.4], [5, 13.4], [13, 64], [13.5...",[Many cars are driving on the horizontal road ...
Explosion007_x264,543.00,"[[0, 20.6], [0, 9.2], [0.6, 16.7], [1.1, 22.6]...",[A man in white clothes is walking with a bag....
Explosion008_x264,58.39,"[[0, 34.1], [34.1, 58.3]]","[There are many vehicles driving on the road.,..."
Explosion009_x264,36.70,"[[0, 7.2], [7.2, 19.3]]","[Two men, one is smoking and the other is walk..."
Explosion010_x264,83.27,"[[3.1, 48.1], [48.8, 79.3]]","[An explosion occurred in the distance, accomp..."
Explosion011_x264,52.38,"[[0, 52.3], [25.5, 30.2], [27.6, 33.8]]",[A large number of vehicles and pedestrians ar...
Explosion012_x264,24.50,"[[0, 4.2], [4.2, 8.6], [4.8, 9.1]]",[A black car was driving and an explosion occu...
Explosion013_x264,110.57,"[[0, 24.9], [24.9, 37.2], [37.2, 52.1], [52.1,...","[A tanker truck drove into the gas station, an..."
Explosion014_x264,43.18,"[[0, 41.5], [9.8, 41.5], [15.5, 20.6], [19.8, ...","[Many cars are driving on the road., A fast-mo..."
Explosion015_x264,29.37,"[[0, 7.4], [5.6, 8.1], [12.2, 18.2]]",[A white car is still driving with a fire in t...
Explosion016_x264,32.16,"[[3.3, 29.3]]",[An explosion occurred in the distant building...
Explosion017_x264,54.81,"[[0, 8.3], [2.5, 9.5], [5.4, 8.5], [0, 54.8], ...",[A man in white rode a motorcycle and parked n...
Explosion018_x264,51.11,"[[0, 4.9]]",[ White smoke and sparks came out of the pocke...
Explosion019_x264,12.01,"[[0, 12]]",[A man in blue was walking and suddenly someth...
Explosion020_x264,43.07,"[[0, 7.3], [5.7, 12.6], [5.7, 11.9], [24.2, 32...",[A man stood next to a black car and communica...
Explosion021_x264,26.24,"[[0, 13.8]]",[There was a sudden explosion at the gas stati...
Explosion022_x264,119.80,"[[0, 5.1], [5.1, 12.7], [11.5, 16.6], [19.7, 2...","[In a room with many machines, a man squatted ..."
Explosion023_x264,77.97,"[[15.7, 77.9], [37.9, 56.9], [65.1, 77.9]]","[The machine emits a large number of sparks, e..."
Explosion024_x264,42.09,"[[8.3, 14.5], [28.1, 42], [31.9, 36]]","[Three people passed by., A large amount of wh..."
Explosion025_x264,16.86,"[[0, 14.6]]","[An explosion occurred in the distance, and a ..."
Explosion026_x264,86.23,"[[0, 3.4], [0, 3.4], [0, 3.4], [3.4, 12.8], [1...",[A woman in brown clothes is walking on the ro...
Explosion027_x264,25.89,"[[0, 3.8], [3.8, 7.5], [7.5, 15.1], [15.1, 25.8]]","[A man is sitting, and another man is sitting ..."
Explosion028_x264,56.92,"[[0, 9], [9, 21.3], [12.8, 56.9]]",[There are many cars parked on the roadside an...
Explosion029_x264,80.33,"[[0, 5.8], [6.1, 10.3], [10.3, 14.4], [14.4, 1...",[A black car is coming from the right. It is p...
Explosion030_x264,108.13,"[[0, 10], [19.2, 24.5], [24.5, 108], [24.5, 34...","[There were many cars parked in a parking lot,..."
Explosion032_x264,70.68,"[[0, 5.1], [5.1, 9.5], [13.4, 25]]","[There are cars driving on a road, and there a..."
Explosion033_x264,105.21,"[[0, 25.6], [32.4, 44.5], [51.2, 105]]","[On the road on the left, a large oil tanker i..."
Explosion034_x264,13.89,"[[0, 13]]",[The white house in the middle of the picture ...
Explosion035_x264,95.50,"[[0, 8.9], [9, 22.3], [22.3, 34], [34, 41.2], ...",[There is a table on the right side of an offi...
Explosion036_x264,177.61,"[[0, 65.3], [65.7, 76.5], [76.5, 100.6], [100....","[In an open space, there are several children ..."
Explosion037_x264,32.09,"[[4.7, 15]]",[An explosion occurred next to the road. Leave...
Explosion038_x264,90.12,"[[4.5, 16.3], [55.6, 61.3], [67, 79.1]]","[There was an explosion in a house, and a larg..."
Explosion039_x264,33.27,"[[2.8, 9.5], [10, 16.5], [16.5, 18.6]]","[An explosion occurred in a restaurant, and th..."
Explosion040_x264,152.47,"[[0, 10.9], [8.2, 33], [33.2, 36.4], [40, 52.9...","[In a room with yellow floors, a woman in blac..."
Explosion041_x264,91.83,"[[1, 4.1], [6.1, 86.2], [86.2, 91]]","[In a vacant lot, a white pickup truck drove o..."
Explosion042_x264,92.29,"[[0, 3.2], [3.2, 31.5], [31.5, 92]]","[Many people are standing at an intersection, ..."
Explosion043_x264,255.00,"[[0, 13], [13.6, 29.8], [21.1, 30.4], [39.5, 4...",[There are two dogs standing in the middle of ...
Explosion044_x264,24.08,"[[3.3, 24]]",[A building at the corner of the road exploded...
Explosion045_x264,25.25,"[[0, 20.3], [20.3, 25]]",[There are vehicles driving on the road at nig...
Explosion046_x264,4730.04,"[[0, 297.4], [3, 228.4], [260.7, 390.5], [419....",[Many vehicles with lights on are passing by i...
Explosion047_x264,46.29,"[[0, 37.1], [37.1, 46]]","[Two cars parked at a gas station, A car sudde..."
Explosion048_x264,15.33,"[[2.8, 6]]","[An explosion occurred in a room, igniting pur..."
Explosion050_x264,9.25,"[[3, 9]]","[There were many cars parked on the road, and ..."
Explosion051_x264,94.00,"[[0, 24], [24, 73.5], [35.6, 49.5], [49.5, 94]]","[A large white truck parked on the roadside, T..."
Explosion052_x264,121.89,"[[0, 30], [30, 121]]","[In a large factory, there are two small puffs..."

,duration,timestamps,sentences
video_id,,,
Fighting002_x264,89.68,"[[0, 2.2], [2.5, 5.8], [4.3, 6], [6.3, 8], [8....","[Several men talking at the bar, A woman with ..."
Fighting003_x264,103.44,"[[0.3, 18], [17.7, 25.9], [34.6, 49.2], [55.2,...","[Pedestrians passing by on the platform, A man..."
Fighting004_x264,559.28,"[[0.7, 2.7], [3.4, 14.7], [3.4, 14.7], [14.6, ...","[ Behind the pool table, a man in black punche..."
Fighting005_x264,59.47,"[[1.3, 9.2], [8.3, 11.6], [23, 26.3], [32.5, 4...",[A man on the lower left is communicating with...
Fighting006_x264,31.47,"[[0, 7.2], [7.2, 10.1], [10.2, 17], [10.2, 17]...",[A man in white and a woman in black sit in th...
Fighting007_x264,126.47,"[[1.6, 10.6], [10.6, 126.1], [10.6, 17.1], [18...",[ Four men beat one man in the center of the s...
Fighting008_x264,437.80,"[[0, 25.2], [26.2, 44.2], [45.4, 59], [59.3, 6...",[Three people came here on motorcycles and wal...
Fighting009_x264,71.07,"[[0.8, 17.8], [19.9, 46.7], [52.1, 58.8], [52....","[A few people jumped and danced, and a row of ..."
Fighting010_x264,195.50,"[[9.3, 17.5], [23.5, 45.9], [56.9, 60.9], [60....",[Many people stood in front of the store on th...
Fighting011_x264,274.67,"[[0.2, 17.2], [20.6, 43.4], [47.3, 58.9], [62....",[Three men lying on the ground and three men s...
Fighting012_x264,38.97,"[[0, 11.9], [15, 31.6]]","[Two men went out to fight, and one man was kn..."
Fighting013_x264,47.80,"[[0, 3.1], [2.1, 9.2], [10.1, 12.1], [12.1, 16...",[A short-sleeved man appeared at the door oppo...
Fighting014_x264,156.83,"[[0, 9.3], [15.8, 37.1], [46.1, 58.1], [62.2, ...","[A group of people dancing in the screen, Joi..."
Fighting015_x264,330.94,"[[0, 68.7], [73.1, 81], [81.1, 85], [84.5, 95....","[A man is wiping a wine bottle at the counter,..."
Fighting016_x264,96.85,"[[0, 2.2], [0, 2.2], [2.3, 11.8], [13.5, 25.7]...",[A man in black and wearing a hat is threateni...
Fighting017_x264,69.27,"[[0.6, 12.9], [2.6, 4.9], [2.6, 14.9], [16.8, ...",[Two men on the side of the road walked to the...
Fighting018_x264,46.37,"[[1.6, 2.4], [3.2, 6.7], [6.2, 8.7], [8.2, 11....",[A man snatched the mobile phone of a woman st...
Fighting019_x264,107.24,"[[13.6, 20], [20.3, 22.7], [20.3, 23.7], [23.7...","[Several men are playing billiards, The man in..."
Fighting020_x264,73.69,"[[0, 1.3], [1.3, 2.3], [2.3, 4.3], [3.3, 7], [...","[Two women had a quarrel on the road, The woma..."
Fighting021_x264,118.96,"[[2.4, 10], [0, 15.7], [15, 20.7], [16, 32.7],...",[A car was parked on the roadside and then a c...
Fighting022_x264,145.15,"[[1.3, 19.4], [20.4, 44.7], [20.4, 44.7], [52....",[A man in black and a man in shorts and a shir...
Fighting023_x264,34.17,"[[8.5, 10.4], [11.5, 12.7], [12.7, 22.5], [22....",[A man in black wearing a white hat and holdin...
Fighting024_x264,218.17,"[[2.2, 5.9], [5.9, 7.9], [6.1, 6.9], [7.1, 27....",[The man in the orange shirt grabbed the man i...
Fighting025_x264,159.41,"[[1, 9.1], [10.6, 19.6], [21, 25.7], [25.9, 42...",[A man in a black vest and another man in whit...
Fighting026_x264,116.84,"[[7, 10.3], [11, 14.3], [14, 23.3], [23.3, 25....",[A man in an orange shirt is eating in the low...
Fighting027_x264,128.45,"[[0.9, 9.6], [10.5, 25.4], [25.4, 46.9], [46.9...",[Two men in white and a man in black had a dis...
Fighting028_x264,80.86,"[[4.9, 17.8], [18.8, 27.3], [31.8, 37.3], [35....",[Two men walked in and one threatened the othe...
Fighting029_x264,145.88,"[[2.8, 12.9], [12.8, 22.9], [23.8, 33.1], [37....",[A man in gray striped clothes punched the man...
Fighting030_x264,74.70,"[[0.7, 10.8], [17.1, 31.6], [38.9, 45.6], [47....",[ Several people were communicating on the rig...
Fighting031_x264,300.06,"[[0, 13.7], [17.6, 27.3], [29.1, 32.3], [32.1,...","[A group of people walked by, Two cars drove a..."
Fighting032_x264,44.83,"[[3, 9.9], [10.1, 15.6], [16.1, 17.6], [17.6, ...",[A man appeared at the counter carrying a fluo...
Fighting033_x264,36.89,"[[1.5, 7.5], [5.5, 8.5], [7.5, 14], [14.5, 18....","[A couple passes by two men, A man in blue aga..."
Fighting034_x264,208.89,"[[0, 10], [10, 27.2], [27.2, 31.5], [35.9, 39....","[A bus leaves, The two people got out of the c..."
Fighting035_x264,32.03,"[[0, 3], [4.1, 19.8], [22.8, 29.6]]","[Two people arguing in the lower right corner,..."
Fighting036_x264,126.03,"[[0, 11.5], [11.5, 21.7], [23.5, 26.7], [42.6,...","[Two men and five men fighting in the street, ..."
Fighting037_x264,145.37,"[[6.7, 16.5], [16.5, 20.2], [20.5, 32.2], [27....","[A car stopped at the door, The co-pilot man g..."
Fighting038_x264,26.86,"[[3.6, 10.7], [11.3, 13.7], [14.9, 18.2], [18....","[Two men in white quickly ran into the store, ..."
Fighting039_x264,227.40,"[[0, 6.9], [0, 15.8], [15, 25.8], [26.4, 38.4]...","[A group of people walking by the roadside, A ..."
Fighting040_x264,77.68,"[[0.7, 13.6], [11.8, 20.8], [53.1, 63], [20.8,...",[Several motorcycles are coming and going in t...
Fighting041_x264,1054.78,"[[4, 9.7], [10.7, 23.1], [20.1, 32.6], [30.6, ...","[A man left with a drink in his hand, There ar..."
Fighting042_x264,74.59,"[[0, 8.2], [8.1, 25.4], [25.8, 29.2], [30.8, 3...","[Security patrolling the door, A man wearing a..."
Fighting043_x264,104.79,"[[9, 17.6], [17.6, 26.3], [26.3, 41.6], [42.4,...","[Two men came over and opened the car door, A ..."
Fighting044_x264,209.64,"[[2.9, 15.9], [12.9, 15.9], [17.7, 27.1], [27....","[How many people came in?, One person was knoc..."
Fighting045_x264,197.17,"[[2, 11.4], [26.9, 34.2], [52.3, 68.2], [92.9,...",[ Several people walked out of the door and ga...
Fighting046_x264,99.93,"[[2.8, 13.3], [32.8, 45.9], [71.4, 93.9], [13....","[ Several men walked out, The crowd moved forw..."
Fighting047_x264,148.69,"[[2.5, 6], [22.5, 32.2], [68.5, 84.1], [105.1,...",[Two men walked in and then hit each other to ...
Fighting048_x264,229.60,"[[12.3, 23.8], [38.3, 48.8], [96.1, 104.8], [1...","[Several men had a dispute in the street, The ..."
Fighting049_x264,51.71,"[[0.7, 12], [15.5, 28.2], [43.3, 50.9], [28.2,...","[A man punched and kicked a sitting man, and t..."
Fighting050_x264,875.51,"[[4.1, 18.3], [82.6, 93.1], [134.7, 168.9], [1...","[A man stood up and talked with another man, T..."
Fighting051_x264,220.27,"[[0, 11.3], [11.4, 24.3], [25.1, 39.3], [39.1,...",[Two men on the right walked to the two sittin...

,duration,timestamps,sentences
video_id,,,
Normal_Videos_003_x264,94.11,"[[21.1, 37.1], [37.1, 45.0], [37.1, 45.0], [45...","[In a second-floor balcony corridor, a yellow ..."
Normal_Videos_006_x264,15.02,"[[0.0, 15.0], [0.4, 7.8]]",[There are many vehicles driving on the small ...
Normal_Videos_010_x264,35.14,"[[5.0, 7.0], [7.0, 10.0], [10.0, 11.3], [10.9,...",[The little boy standing in front of the camer...
Normal_Videos_014_x264,50.04,"[[0.0, 9.6], [9.6, 12.5], [12.5, 14.6], [29.1,...",[The cashier collects the customer's money and...
Normal_Videos_015_x264,16.05,"[[0.0, 3.3], [0.0, 6.4], [0.0, 11.4], [11.0, 1...","[A woman wearing a white top and black pants, ..."
Normal_Videos_018_x264,39.43,"[[22.2, 25.7], [29.8, 32.2], [35.2, 37.4], [37...",[There are multiple people dressed in black wa...
Normal_Videos_019_x264,94.84,"[[0.0, 4.1], [9.2, 11.1], [5.2, 13.1], [16.6, ...",[The woman with blond hair and black clothes i...
Normal_Videos_024_x264,35.95,"[[0.0, 6.0], [0.0, 7.7], [7.7, 11.7], [4.0, 7....","[On the left side of the screen, two fat men i..."
Normal_Videos_025_x264,20.11,"[[0.0, 4.4], [2.6, 7.3], [10.0, 18.0], [18.0, ...","[ Far away in the office, a tall, thin man in ..."
Normal_Videos_027_x264,164.10,"[[0.0, 4.2], [7.7, 15.7], [15.7, 22.6], [22.7,...",[There is a man with a black hat and blue stri...
Normal_Videos_033_x264,56.03,"[[19.9, 22.2], [19.9, 22.2], [22.2, 26.6], [27...","[A pair of men and women with short hair, wear..."
Normal_Videos_034_x264,43.98,"[[0.0, 2.0], [1.6, 8.6], [1.6, 8.6], [1.6, 8.6...",[There are two white cars passing by in the up...
Normal_Videos_041_x264,42.38,"[[0.0, 8.0], [8.0, 11.7], [11.3, 18.7], [18.3,...",[The cashier in the lower left corner is colle...
Normal_Videos_042_x264,105.21,"[[0.0, 4.1], [0.0, 4.1], [4.1, 12.5], [12.5, 2...",[Two cashiers in white shirts are communicatin...
Normal_Videos_048_x264,55.62,"[[21.4, 23.9], [23.9, 28.7], [30.6, 37.5], [37...",[A man in the distance stood up and walked to ...
Normal_Videos_050_x264,139.95,"[[0.0, 12.5], [0.0, 12.5], [12.5, 26.9], [12.5...",[There are sparse road vehicles on the left si...
Normal_Videos_196_x264,66.83,"[[0.0, 9.4], [9.4, 17.5], [19.6, 29.8], [37.6,...",[There are five men talking to each other in t...
Normal_Videos_051_x264,78.65,"[[0.0, 8.4], [8.4, 15.6], [43.3, 46.9]]",[There is a white old man nearby crossing the ...
Normal_Videos_056_x264,52.43,"[[0.0, 6.8], [7.4, 11.9], [0.4, 10.9], [11.9, ...",[There is a woman in red putting things on the...
Normal_Videos_059_x264,61.29,"[[0.0, 5.2], [0.0, 7.2], [7.0, 10.2], [10.0, 1...","[Man in white shirt leaves, The man in blue sh..."
Normal_Videos_063_x264,11.89,"[[0.0, 2.6], [0.0, 2.6], [0.0, 2.6], [0.0, 7.1...","[The first cashier, the male cashier in blue s..."
Normal_Videos_067_x264,35.60,"[[0.0, 3.0], [3.4, 10.8], [20.1, 24.9], [24.9,...",[The repairman with black and orange stripes e...
Normal_Videos_070_x264,33.16,"[[0.0, 3.3], [3.3, 5.0], [3.3, 5.0], [5.3, 14....",[The curly long-haired woman entered the scree...
Normal_Videos_100_x264,20.95,"[[11.2, 13.2]]",[The man in blue walks out of the camera]
Normal_Videos_129_x264,15.57,"[[11.3, 13.4]]",[The administrator in orange clothes is direct...
Normal_Videos_150_x264,28.84,"[[6.4, 8.8], [14.6, 23.6], [14.6, 23.6]]","[The man in black comes from the left aisle, A..."
Normal_Videos_168_x264,58.00,"[[5.6, 9.6], [9.6, 16.1], [16.1, 18.1], [18.1,...",[Two pedestrians are crossing the road in the ...
Normal_Videos_175_x264,294.96,"[[0.0, 6.9], [6.9, 26.9], [26.2, 36.9], [37.9,...","[A bald head walked through the workshop, No o..."
Normal_Videos_182_x264,136.51,"[[60.1, 69.9], [69.9, 77.4]]",[A courier in red came in and chatted with the...
Normal_Videos_189_x264,24.59,"[[1.3, 9.3], [1.3, 9.3]]","[Many red cars shuttle on the road, Many white..."
Normal_Videos_203_x264,85.75,"[[5.3, 12.0], [22.1, 27.9], [43.4, 66.6]]",[The yellow bus drives past from left to right...
Normal_Videos_210_x264,180.33,"[[20.4, 26.6], [77.1, 82.3], [92.5, 108.5], [1...","[White car parked on the roadside, There is a ..."
Normal_Videos_217_x264,60.60,"[[3.6, 10.2], [19.6, 24.0], [45.5, 49.4]]","[Khaki woman walks from near to far, The old m..."
Normal_Videos_224_x264,231.97,"[[23.7, 25.4], [23.7, 25.4], [40.6, 50.9], [40...",[The black woman gives the customer a manicure...
Normal_Videos_246_x264,166.46,"[[75.0, 100.0]]",[Many construction team members came to the ha...
Normal_Videos_247_x264,273.74,"[[25.7, 68.5]]",[The cashier collects money for customers step...
Normal_Videos_248_x264,38.04,"[[9.5, 19.6], [35.4, 36.4]]",[Many people came out of the hall and raised b...
Normal_Videos_251_x264,13.53,"[[4.3, 7.0], [9.5, 13.5]]",[A black man and an Asian man entered the hous...
Normal_Videos_289_x264,28.80,"[[11.7, 18.2], [11.7, 18.2]]",[The teacher in red is writing on the blackboa...
Normal_Videos_310_x264,83.99,"[[0.0, 4.3], [29.1, 31.5], [46.6, 55.3]]","[The boys made the shot, The boy in white made..."
Normal_Videos_312_x264,42.03,"[[0.0, 3.2], [3.2, 9.2], [9.2, 27.2], [11.2, 3...",[A male customer walks from the middle to the ...
Normal_Videos_317_x264,30.97,"[[0.0, 3.3], [3.0, 6.3], [6.9, 25.9]]",[There is a female receptionist sitting in fro...
Normal_Videos_345_x264,7.04,"[[0.0, 6.5], [0.0, 6.5]]",[A balding man communicates with 2 staff at th...
Normal_Videos_352_x264,180.14,"[[0.0, 10.2], [10.0, 13.2], [0.0, 62.2], [0.0,...",[There is a white car parked in front of the c...
Normal_Videos_360_x264,32.83,"[[0.0, 5.3], [0.0, 11.3], [12.0, 19.3], [6.0, ...","[Customers come to the counter, The cashier st..."
Normal_Videos_365_x264,220.96,"[[0.0, 63.3], [0.0, 165.3], [0.0, 129.3], [73....","[ Looking down at the bottom of the screen, a ..."
Normal_Videos_401_x264,54.24,"[[22.5, 27.8], [42.4, 50.0], [42.4, 50.0]]",[The old man in electric wheelchair walks acro...
Normal_Videos_439_x264,140.90,"[[17.4, 21.7], [17.4, 21.7], [21.7, 33.3]]","[The fat man talks to the man in the glass, Ma..."
Normal_Videos_452_x264,14.84,"[[7.0, 10.6]]",[People in blue clothes and green clothes are ...
Normal_Videos_453_x264,177.42,"[[15.1, 36.4], [36.4, 45.2], [93.0, 110.8], [1...",[An old man walked in from the door and commun...
Normal_Videos_478_x264,150.07,"[[17.6, 20.4], [27.5, 37.0], [66.6, 75.6]]","[A woman in black walked away along the road, ..."
Normal_Videos_576_x264,375.89,"[[11.6, 18.5], [18.5, 20.5], [34.3, 40.3], [10...","[Two men are walking along the road, A black a..."
Normal_Videos_597_x264,74.35,"[[0.5, 13.9], [17.3, 20.0], [20.3, 27.0], [25....",[A man moved from the left side of the counter...
Normal_Videos_878_x264,9.37,"[[1.5, 9.3]]",[A man in black walked to the left from the in...

,duration,timestamps,sentences
video_id,,,
Normal_Videos001_x264,18.14,"[[0.0, 11.3], [4.2, 10.5], [9.1, 15.7]]",[A fat man in a blue shirt stood behind the gl...
Normal_Videos002_x264,55.50,"[[0.0, 12.1], [12.3, 15.8], [19.2, 26.9], [31....",[ Several cardboard boxes blocked most of the ...
Normal_Videos_003_x264,94.11,"[[21.1, 37.1], [37.1, 45.0], [37.1, 45.0], [45...","[In a second-floor balcony corridor, a yellow ..."
Normal_Videos004_x264,30.60,"[[0.0, 1.3], [0.8, 3.1], [7.5, 11.2], [12.2, 1...",[A man wearing a white shirt and glasses stood...
Normal_Videos005_x264,12.91,"[[0.0, 0.8], [1.0, 6.1], [1.8, 8.9], [4.1, 11.9]]","[A gray car drove past the corner, a white car..."
...,...,...,...
Normal_Videos194_x264,138.12,"[[2.9, 6.5], [9.1, 18.1], [0.0, 37.1], [40.1, ...",[A man in a black shirt and gray pants walked ...
Normal_Videos195_x264,158.53,"[[0.0, 11.2], [10.3, 33.4], [46.9, 63.2], [79....",[A man in white clothes and black pants is wal...
Normal_Videos197_x264,82.20,"[[0.0, 7.3], [15.2, 25.1], [25.8, 27.1], [28.2...",[The woman in the gray top went out while turn...
Normal_Videos198_x264,74.77,"[[0.0, 15.1], [3.1, 19.5], [69.2, 74.1]]",[The black car is coming and turns right with ...
Normal_Videos199_x264,234.48,"[[0.0, 234.2], [4.5, 36.2], [7.1, 46.3], [171....",[The bank staff has been counting the number o...

,duration,timestamps,sentences
video_id,,,
Normal_Videos_925_x264,257.58,"[[0.1, 13.1], [14.6, 16.9], [31.6, 32.9], [34....","[Someone is walking in the dark night, A car d..."
Normal_Videos_926_x264,59.91,"[[0.0, 3.3]]",[A man came over with a box]
Normal_Videos_928_x264,30.65,"[[0.8, 3.3], [2.6, 13.6], [12.5, 15.5], [16.6,...","[The salesperson is talking to the customer, T..."
Normal_Videos_929_x264,30.92,"[[0.7, 10.7], [12.6, 14.6], [24.1, 29.1]]",[Two people came to the counter to chat with t...
Normal_Videos_930_x264,106.30,"[[0.0, 2.6], [3.8, 6.5], [6.1, 13.1], [8.3, 14...","[Someone is walking in the distance, The fish ..."
...,...,...,...
Normal_Videos393_x264,97.29,"[[7.4, 12.0], [14.7, 16.7], [17.0, 21.2], [22....",[A woman in red clothes and a woman in white c...
Normal_Videos394_x264,61.05,"[[0.3, 6.6], [13.2, 17.1], [30.2, 47.7], [50.0...",[A woman in gray clothes walked into the store...
Normal_Videos395_x264,16.05,"[[0.2, 16.0]]","[A shop without people, with many things on th..."
Normal_Videos398_x264,124.73,"[[0.6, 10.4], [12.7, 27.2], [26.5, 40.0], [36....","[A white truck drove past, A white van drove p..."
Normal_Videos399_x264,113.37,"[[0.5, 8.7], [0.5, 5.5], [5.6, 11.7], [11.4, 2...",[A cleaner walks from the right to the left un...

,duration,timestamps,sentences
video_id,,,
Normal_Videos400_x264,23.96,"[[3.2, 10.4], [14.1, 23.0]]",[A man in white walked to the end of the corri...
Normal_Videos_401_x264,54.24,"[[22.5, 27.8], [42.4, 50.0], [42.4, 50.0]]",[The old man in electric wheelchair walks acro...
Normal_Videos402_x264,19.41,"[[0.0, 19.4], [0.8, 19.4], [0.5, 19.4], [2.8, ...",[There are people constantly passing between t...
Normal_Videos403_x264,13.89,"[[0.9, 13.8], [0.3, 13.2], [0.3, 13.7]]",[Several people at supermarket checkout are ta...
Normal_Videos404_x264,115.80,"[[15.3, 20.7], [23.1, 42.6], [20.9, 47.5], [48...","[A man opens the back door of a yellow car, A ..."
...,...,...,...
Normal_Videos822_x264,62.56,"[[7.1, 23.1], [19.0, 26.2], [26.2, 36.1], [38....",[Two women came from the right and walked into...
Normal_Videos823_x264,45.44,"[[16.7, 21.3], [21.3, 24.2]]","[In an indoor passage, a man in a blue shirt p..."
Normal_Videos824_x264,45.58,"[[20.8, 31.1], [31.2, 35.0]]","[In the hall, a man wearing a plaid shirt and ..."
Normal_Videos825_x264,53.73,"[[23.2, 35.1], [28.2, 35.3], [29.0, 42.1]]",[A man in a white shirt walks from the bottom ...
Normal_Videos826_x264,55.26,"[[20.2, 34.2], [35.2, 44.0]]",[A woman wearing pink clothes walked out of th...

,duration,timestamps,sentences
video_id,,,
Normal_Videos_934_x264,58.89,"[[33.9, 36.9], [42.8, 52.8]]",[A man wearing a blue hat came to the store to...
Normal_Videos601_x264,82.48,"[[0.0, 15.2], [15.2, 35.4], [35.4, 78.0], [78....",[Several vehicles passed by on a highway. A bl...
Normal_Videos602_x264,383.52,"[[0.0, 10.1], [10.1, 33.5], [33.5, 70.3], [70....","[A road is covered with white snow, and a blac..."
Normal_Videos_603_x264,109.27,"[[2.3, 8.3], [25.0, 41.6], [58.3, 71.6], [8.3,...",[Man in pink shirt is looking for something on...
Normal_Videos604_x264,48.11,"[[0.0, 13.3], [13.3, 35.1]]","[On a road, several passers-by walked down and..."
...,...,...,...
Normal_Videos796_x264,558.27,"[[0.0, 14.3], [24.5, 39.7], [42.8, 47.0], [61....","[On the right side of the road, a light blue t..."
Normal_Videos797_x264,93.60,"[[0.0, 5.6], [6.7, 10.6], [11.6, 17.1], [23.5,...","[On the sidewalk on the left side of the road,..."
Normal_Videos_798_x264,200.03,"[[17.4, 21.7], [30.2, 35.2], [61.5, 71.5], [61...","[A blue car drove past, Two white cars drove p..."
Normal_Videos799_x264,122.09,"[[0.0, 22.5], [23.4, 25.2], [26.3, 67.1], [68....","[Two men were sitting and chatting in a room, ..."
Normal_Videos800_x264,15.63,"[[0.0, 15.1]]","[In a bustling square, the lights are bright. ..."

,duration,timestamps,sentences
video_id,,,
Robbery001_x264,33.04,"[[0, 5.3], [5.3, 8.2], [10.3, 15.6], [15.6, 18...",[A man wearing gray short-sleeves and a white ...
Robbery002_x264,106.77,"[[2.1, 6.1], [6.4, 16.8], [21.9, 31], [31, 38....",[The head of a man with long white hair enters...
Robbery003_x264,32.88,"[[0.5, 10.3], [10.3, 14.2], [15.5, 18.2], [18....",[A man wearing a hat and a black and white pla...
Robbery004_x264,51.05,"[[0, 5.5], [0, 5.5], [7.6, 12.2], [7.6, 12.2],...",[A long-haired woman wearing a black and red t...
Robbery005_x264,92.00,"[[7.7, 14.5], [15.9, 20.6], [20.7, 27.7], [27....",[A man in a blue hoodie suddenly ran into the ...
Robbery006_x264,113.30,"[[1.1, 15.8], [15.8, 18.3], [19.9, 23.2], [19....",[The black man with a backpack pushed the man ...
Robbery007_x264,68.80,"[[1.7, 8.3], [8.3, 12.4], [19.5, 29.7], [17.5,...","[A man wearing a green shirt enters the room, ..."
Robbery008_x264,75.23,"[[1.2, 11.2], [1.2, 11.2], [11.2, 20.8], [19.3...","[There are two men in hoodies looking around, ..."
Robbery009_x264,106.77,"[[0, 7.6], [7.6, 27.9], [20.2, 32.9], [33.4, 4...","[A little girl walked to the shelf, Two teller..."
Robbery010_x264,102.03,"[[0, 13.3], [23.1, 29.6], [29.6, 34.7], [34.7,...",[A man wearing black short sleeves turned arou...
Robbery011_x264,54.23,"[[10.6, 15.5], [10.6, 15.5], [18, 21.2], [21.2...",[A man in black wearing a silver helmet walked...
Robbery012_x264,24.97,"[[1, 8.4], [8.4, 10.1], [10, 15.2], [11, 15.2]...",[A black-haired man wearing a red shirt sat ne...
Robbery013_x264,121.30,"[[1, 6.1], [7.4, 10.5], [11, 14.2], [14.2, 20]...",[A man in black wearing a hat and holding a gu...
Robbery014_x264,509.27,"[[0, 20.2], [14.1, 20.2], [24.1, 32.1], [32.1,...",[A white-haired man wearing a gray short-sleev...
Robbery015_x264,91.30,"[[0.5, 3.2], [3.2, 5], [6, 8.7], [6, 8.7], [9....","[A man wearing a hat, a blue backpack and a bl..."
Robbery016_x264,55.10,"[[1, 6.1], [6.1, 9], [10.3, 19.3], [10.3, 19.3...",[A man wearing a helmet walked into the superm...
Robbery017_x264,145.27,"[[1.1, 6.5], [6.5, 19.6], [19.6, 25.5], [25.5,...",[There is a man and a woman at the counter. Th...
Robbery018_x264,95.97,"[[1.5, 5.3], [5.3, 7.8], [8.9, 10.6], [10.6, 1...",[A man wearing a red short-sleeved shirt at th...
Robbery019_x264,192.03,"[[0, 3], [3, 12.1], [12.7, 18.8], [18.8, 24.4]...",[There are three men sitting at the counter co...
Robbery020_x264,146.77,"[[1, 4.2], [4.2, 9.8], [10.9, 15.2], [23.2, 25...",[A man wearing a yellow short-sleeved shirt op...
Robbery021_x264,274.10,"[[4.3, 7.9], [7.9, 10.6], [12.1, 22.9], [12.1,...",[A man in a blue hoodie and a man in a gray ho...
Robbery022_x264,117.10,"[[0, 5.4], [5.4, 14.2], [14.2, 20.7], [21.3, 1...",[A woman in red stands in front of the ATM mac...
Robbery023_x264,37.03,"[[2.1, 4.5], [4.5, 9.8], [10.2, 20.8], [10.2, ...",[The two women sitting at the counter suddenly...
Robbery024_x264,79.83,"[[2.8, 26.7], [2.8, 26.7], [2.8, 26.7], [27.5,...",[A man in white and a man in black are fightin...
Robbery025_x264,48.87,"[[1.8, 4.4], [4.4, 7.7], [8.4, 15.5], [9.5, 22...",[A man wearing a turban and holding a long gun...
Robbery026_x264,437.17,"[[7.2, 45], [45, 55.5], [59.7, 73.6], [73.6, 8...","[ In the picture, a woman in black and a man i..."
Robbery027_x264,180.00,"[[1.6, 12.2], [12.2, 21.2], [25, 36.8], [25, 3...",[A man wearing a white short-sleeved shirt cam...
Robbery028_x264,78.07,"[[2.8, 17.6], [2.8, 17.6], [19.3, 30.1], [30.1...","[ Walked in from the door, one black and one w..."
Robbery029_x264,72.77,"[[1.1, 24.2], [24.2, 27.3], [27.3, 30.4], [27....","[ Four men got out of a white van, three of th..."
Robbery030_x264,99.20,"[[10.1, 18.5], [19.9, 35.4], [39.7, 75.6], [75...",[The screen lights up with three men entering ...
Robbery031_x264,36.90,"[[0.5, 6.4], [6.4, 12.3], [12.3, 27.4], [27.4,...","[A motorcycle passed by, Two women walked to t..."
Robbery032_x264,180.00,"[[0, 23.5], [8, 12.6], [22.3, 25.8], [30.5, 33...",[A long-haired woman in white clothes is walki...
Robbery033_x264,31.67,"[[0.7, 5.4], [5.4, 14.1], [16.1, 18.2], [16.1,...",[A man in gray clothes entered the store with ...
Robbery034_x264,211.07,"[[10.5, 20.2], [10.5, 11.2], [26.5, 31.2], [37...","[Several men entered with guns, The man in whi..."
Robbery035_x264,155.37,"[[7.5, 24.9], [1.5, 5.9], [35.6, 49.7], [54.4,...",[One person is sitting at the table and the ot...
Robbery036_x264,205.70,"[[2, 10.6], [9.6, 12.2], [18.4, 25.8], [18.4, ...",[Three people communicating at the workstation...
Robbery037_x264,290.90,"[[1.1, 20.7], [21.1, 29.6], [35, 44], [47.1, 6...",[A man in white clothes and black pants is sit...
Robbery038_x264,61.07,"[[2.5, 10.9], [12.8, 24.5], [29.1, 51.1], [51....",[A motorcycle carrying a man in yellow and a m...
Robbery039_x264,17.50,"[[0.6, 10.5], [10.5, 13.2], [13.2, 16.2]]",[A masked man entered and took a white item fr...
Robbery040_x264,34.80,"[[2.4, 10.5], [23.2, 29.2]]",[A man in blue and white hat entered and stood...
Robbery041_x264,45.57,"[[0.4, 11.1], [3.1, 6.3], [11.2, 16.3], [17, 2...",[A man entered with a gun and held a man hosta...
Robbery042_x264,72.40,"[[0.9, 9.9], [11.4, 17.3], [21.4, 38.2], [38.2...",[A man wearing a black hoodie appeared at the ...
Robbery043_x264,34.60,"[[0.7, 10.6], [14.1, 15.6], [16.6, 25.8], [25,...",[Two men with guns entered. The man in black j...
Robbery044_x264,15.60,"[[0.9, 10.4], [10.4, 15]]",[A man wearing a black hat and a black vest th...
Robbery045_x264,111.03,"[[1.5, 25.8], [33.4, 40.8], [40.4, 45.8], [48....","[A man and a woman are kissing, A man on the l..."
Robbery046_x264,28.40,"[[1.2, 16.2], [14.2, 15.2]]",[A man wearing a helmet stood on the counter w...
Robbery047_x264,50.90,"[[0.9, 13.3], [14.5, 18.9], [18.9, 39], [39, 4...",[A man followed another man with a gun and ent...
Robbery048_x264,47.03,"[[0.3, 16.8], [16.3, 17.8], [17.8, 20.3], [20....",[A man is looking at the closed glass door at ...
Robbery049_x264,66.06,"[[2.1, 12.8], [16.8, 33.3], [34.4, 45.2], [46....","[Three men walked in, A woman pulled out a wea..."
Robbery050_x264,56.75,"[[0.3, 11.5], [14.4, 17.2], [16.4, 20.2], [21....","[A white car came and stopped on the road, A m..."

,duration,timestamps,sentences
video_id,,,
Shooting001_x264,8.52,"[[0, 8.2], [1.1, 3.2], [1.1, 5.2], [5.1, 6.2],...",[There are several people standing at the bar ...
Shooting002_x264,40.30,"[[1.1, 10.1], [4.9, 13.9], [13.6, 15.6], [26.3...","[Three men hugging each other, There are two m..."
Shooting003_x264,76.02,"[[6.1, 13.1], [8.4, 15.6], [10.9, 12.9], [12.2...",[There are three people standing on the roadsi...
Shooting004_x264,59.79,"[[11.4, 14.4], [14.9, 18.9], [15.3, 17.3], [17...","[A policeman ran forward with his gun raised, ..."
Shooting005_x264,177.75,"[[1.9, 4.9], [25, 31.6], [29.8, 32.2], [36.1, ...","[A man entered the house, A man came out of th..."
Shooting006_x264,435.79,"[[0, 23.3], [20, 24.3], [24.2, 29.2], [21.3, 5...",[The man in the white T-shirt walks to the cou...
Shooting007_x264,47.72,"[[1.5, 10.5], [9, 12], [12.5, 15.5], [29.1, 31...",[There is a man in blue clothes walking on the...
Shooting008_x264,54.17,"[[0.8, 3.3], [3.4, 9.4], [3.4, 9.4], [8.3, 12....",[The fat man in black is looking for something...
Shooting009_x264,172.20,"[[3.4, 9.4], [21.5, 31.5], [22.6, 27.6], [29.8...","[Someone came in from a distance, The man in p..."
Shooting010_x264,88.27,"[[35.1, 38.3], [36.1, 45.1], [37.5, 43.5], [40...","[The man entered the car door, A man also came..."
Shooting011_x264,133.48,"[[0, 2], [0, 3.5], [11.1, 21.1], [26, 36], [26...",[People at the counter are talking to each oth...
Shooting012_x264,62.97,"[[18.8, 21.1], [0, 9.6], [9.6, 12.5], [12.5, 1...",[ Someone in the distance opened the trunk of ...
Shooting013_x264,35.87,"[[2.4, 10.4], [11.3, 29.4], [29.9, 30.9], [30,...","[A man walking up the stairs, The man is looki..."
Shooting014_x264,213.69,"[[2.5, 12.5], [6.8, 16.6], [1.5, 10.5], [19.8,...","[A man is talking to a woman, The man got up a..."
Shooting015_x264,57.17,"[[0, 8.4], [0, 6.8], [3.9, 10.9], [7.4, 11.9],...",[There is a white old man nearby crossing the ...
Shooting017_x264,31.45,"[[4.1, 21.5], [2.1, 20.1], [21.4, 25.4], [22.4...","[A man in white sits down, A man in white came..."
Shooting018_x264,60.04,"[[2.4, 4.4], [7.4, 12.4], [12.4, 16.4], [16.5,...",[The man in white walked away carrying somethi...
Shooting019_x264,92.34,"[[1.8, 2.8], [15.2, 17.2], [15.2, 17.2], [18.6...",[Someone is walking in the distance in the dar...
Shooting020_x264,169.76,"[[2.5, 12.5], [8.7, 12.7], [13.7, 17.7], [18, ...","[A person hurriedly walked into the hall, A pe..."
Shooting021_x264,42.67,"[[0, 4.2], [0.8, 11.2], [11.2, 15.8], [15.8, 1...","[A white car drove into the garage, The garage..."
Shooting022_x264,151.94,"[[0, 16.2], [0, 16.2], [16.2, 20.1], [76.8, 86...",[A man in red clothes and red hat stands in th...
Shooting023_x264,13.94,"[[0, 7.2], [7.2, 13]]","[A group of people gathered together, walking ..."
Shooting024_x264,66.80,"[[7.4, 11.9], [17.8, 18.8], [16.7, 18.8], [18....",[Two peeping men rushed straight into the stor...
Shooting025_x264,81.76,"[[25, 31.6], [46, 51.1]]","[A woman points a gun at a man, The woman kill..."
Shooting026_x264,46.80,"[[0, 6.5], [6.5, 13.8], [13.8, 24.2], [33.1, 4...",[A man in a white shirt walked up from the bot...
Shooting027_x264,23.63,"[[0, 5.1], [5.1, 7.2], [14.3, 23]]",[ Several people were running on the road on t...
Shooting028_x264,63.33,"[[0, 3.2], [4.8, 14.8]]",[There is an old man holding something in fron...
Shooting029_x264,45.60,"[[0, 8.3], [0, 8.3], [8.3, 10.3], [13, 21.3], ...","[At night, a car with a white body drove into ..."
Shooting030_x264,40.44,"[[0, 8.5], [2, 7.5], [9.1, 15.8], [13, 20], [2...",[There are four people working in their own po...
Shooting031_x264,70.47,"[[0, 9.2], [8.2, 11.2], [13.3, 20], [20, 24.3]...",[A man wearing black pants and a gray shirt wa...
Shooting032_x264,722.77,"[[0, 17], [17, 23.5], [25.2, 36.3], [25.2, 36....",[The end of the street is a T-intersection wit...
Shooting033_x264,121.05,"[[0, 13.4], [13.4, 31.1], [31.1, 52.5], [52.5,...","[A white off-road vehicle reversed, and a blac..."
Shooting034_x264,47.06,"[[0, 7.3], [7.3, 27.5], [15.8, 20], [20, 43.1]...","[A red SUV is driving on the road, The red SUV..."
Shooting036_x264,127.72,"[[0, 5.2], [5.2, 7.5], [5.2, 6.1], [5.2, 7.2],...",[There are several people in a house. There is...
Shooting037_x264,10.25,"[[0, 10], [1, 8]]","[A black car is parked on the road., There was..."
Shooting038_x264,43.31,"[[7, 12.5], [3, 7], [12.1, 21.2], [29.3, 34.6]...","[There are several people running on a road, A..."
Shooting039_x264,27.73,"[[0, 9.7], [9.7, 18.6], [18.6, 22.1], [22.6, 2...","[In a gas station, a man in black clothes was ..."
Shooting040_x264,28.70,"[[0, 15.1], [15.1, 18.7], [17.6, 20.4]]",[A black car was surrounded by several police ...
Shooting041_x264,46.45,"[[0, 13.1], [13.1, 19.3], [19.1, 46.3]]",[A white car drove quickly on the road and the...
Shooting042_x264,51.61,"[[0, 14.2], [14.2, 34.1], [31.2, 35.1], [34.1,...",[In a store a man stood in front of the counte...
Shooting043_x264,62.55,"[[0, 24.6], [24.6, 36.7], [36.7, 62.5], [36.7,...",[There was a black off-road vehicle parked in ...
Shooting044_x264,15.52,"[[0, 15.5]]","[A white car passed by the road, and a black w..."
Shooting046_x264,169.60,"[[0, 32.9], [32.9, 71.8], [71.8, 134.4], [134....",[A man in a blue plaid shirt is withdrawing mo...
Shooting047_x264,276.23,"[[19.1, 40.2], [40.2, 56], [69.3, 77.5], [78.9...","[There were several cars parked in a yard, and..."
Shooting048_x264,91.39,"[[0, 42.2], [42.2, 53.4], [53.4, 62.6], [62.6,...",[A man in white clothes and a woman in yellow ...
Shooting050_x264,127.73,"[[0, 34.9], [34.9, 51.6], [51.6, 73.6], [73.6,...","[On the road in the evening, several vehicles ..."
Shooting051_x264,46.75,"[[4.4, 12.8], [12.8, 43.3]]",[A yellow motorcycle and a red motorcycle were...
Shooting052_x264,185.60,"[[0, 14.2], [24.8, 29.1], [29.6, 32.1], [35.8,...","[Three people got into the red car, A man in b..."
Shooting053_x264,30.75,"[[0, 20.6], [20.6, 30.2]]",[Two men wearing helmets broke into the gold j...
Shooting054_x264,24.48,"[[0, 4.1], [4.1, 24.4]]",[A man in a black hat holding a bag walked in ...

,duration,timestamps,sentences
video_id,,,
Shoplifting001_x264,144.88,"[[5.2, 21.3], [24.7, 45.9], [46.7, 56.9], [57....",[The man in the orange shirt walked to the mid...
Shoplifting003_x264,360.62,"[[0.0, 10.0], [12.0, 16.7], [17.0, 25.7], [29....",[There were three men in the store. Two women ...
Shoplifting004_x264,222.48,"[[0.0, 6.1], [6.1, 14.4], [14.4, 22.6], [22.6,...",[Man wearing glasses is looking at the items i...
Shoplifting005_x264,65.57,"[[0.0, 10.3], [0.0, 10.3], [10.5, 16.6], [10.5...",[A man wearing a black down jacket and a man w...
Shoplifting006_x264,105.20,"[[0.3, 7.9], [8.6, 42.9], [43.3, 56.6], [57.2,...","[A woman picked up a large bottle of water, pu..."
Shoplifting007_x264,170.80,"[[0.0, 7.6], [7.6, 12.4], [12.4, 15.3], [15.3,...",[The woman in orange clothes walks to the door...
Shoplifting008_x264,297.57,"[[1.1, 10.2], [11.2, 14.3], [15.6, 30.8], [31....",[The man next to the boss and three men are ta...
Shoplifting009_x264,173.37,"[[0.3, 11.9], [11.2, 28.6], [28.6, 41.8], [41....",[A man in a shirt walked into a store from out...
Shoplifting010_x264,91.20,"[[0.0, 10.1], [0.0, 10.1], [11.5, 20.3], [11.5...","[In a supermarket, there are all kinds of good..."
Shoplifting012_x264,781.10,"[[79.2, 98.3], [84.2, 98.3], [98.6, 104.3], [1...",[A woman wearing gorgeous traditional Indian c...
Shoplifting013_x264,67.37,"[[1.1, 13.0], [14.5, 25.8], [19.5, 25.8], [26....",[A woman in a blue skirt and a woman with yell...
Shoplifting014_x264,2223.27,"[[0.0, 11.5], [0.0, 11.5], [11.5, 33.6], [33.6...",[A male salesperson in the store touched the c...
Shoplifting015_x264,75.20,"[[1.5, 11.3], [12.3, 23.9], [26.3, 47.2], [47....","[Three men are talking, one with his arms cros..."
Shoplifting016_x264,49.47,"[[0.0, 7.3], [8.2, 14.9], [15.3, 22.8], [23.5,...",[A woman with long black hair wearing a red fl...
Shoplifting017_x264,15.34,"[[0.6, 11.7], [11.7, 15.0], [11.7, 15.0]]",[The man in a gray suit said something to the ...
Shoplifting018_x264,71.16,"[[2.2, 11.1], [7.2, 11.1], [12.4, 28.9], [15.4...",[A woman and a man were walking in the middle ...
Shoplifting019_x264,21.92,"[[6.3, 12.1], [10.3, 12.1], [12.4, 15.5], [12....",[A man wearing two hats suddenly took away a b...
Shoplifting020_x264,192.37,"[[0.1, 6.9], [6.3, 12.5], [12.4, 13.7], [14.4,...",[The picture shows a shop. The boss is a long-...
Shoplifting021_x264,118.41,"[[1.3, 5.3], [6.4, 16.3], [17.2, 22.9], [23.3,...","[In a store, a male boss took an earring from ..."
Shoplifting022_x264,73.07,"[[1.2, 13.0], [16.4, 24.1], [25.2, 32.7], [33....",[Two people entered the supermarket one after ...
Shoplifting024_x264,40.32,"[[2.2, 13.4], [14.1, 25.2], [26.4, 37.6], [38....",[A woman sat outside the table and a man sat a...
Shoplifting025_x264,60.94,"[[1.4, 11.3], [13.2, 23.1], [23.7, 35.3], [23....",[Two women were in a clothing store. The woman...
Shoplifting026_x264,47.09,"[[1.7, 11.4], [11.7, 29.6], [30.1, 45.8], [38....",[A man wearing a floral cloth put a piece of b...
Shoplifting027_x264,62.47,"[[2.3, 15.3], [30.0, 40.9]]",[A man in shorts stayed in front of the glass ...
Shoplifting028_x264,45.28,"[[7.4, 12.6], [13.0, 16.1], [14.0, 21.1], [22....",[A man and a woman were looking at the product...
Shoplifting029_x264,72.56,"[[6.9, 10.8], [7.9, 13.8], [14.6, 27.6], [15.9...",[A man stood in a men's clothing store and pat...
Shoplifting030_x264,806.48,"[[6.5, 20.3], [23.4, 31.3], [36.1, 44.9], [36....","[In a digital store, many people are shopping ..."
Shoplifting031_x264,14.94,"[[1.9, 13.3], [13.7, 14.2]]",[A bald man wearing sunglasses hid something i...
Shoplifting032_x264,47.59,"[[1.9, 10.9], [11.9, 20.2], [22.0, 26.8], [31....","[In a helmet store, two men came in and looked..."
Shoplifting033_x264,30.01,"[[0.9, 10.1], [11.4, 26.9], [27.4, 30.0]]",[The man in a blue shirt touched the watch on ...
Shoplifting034_x264,397.90,"[[23.7, 32.8], [33.3, 40.9], [42.4, 50.1], [53...",[The door opened and a woman in a floral skirt...
Shoplifting036_x264,121.98,"[[2.7, 16.5], [23.8, 31.6], [32.5, 39.0], [39....","[In a room full of clothes, a man in a white s..."
Shoplifting037_x264,46.22,"[[0.8, 8.5], [9.7, 13.1], [11.8, 14.6], [21.0,...","[A man put a piece of jewelry on the table, th..."
Shoplifting038_x264,96.83,"[[1.0, 16.1], [19.8, 38.7], [43.2, 49.6], [51....","[A man walked into the dessert shop, and then ..."
Shoplifting039_x264,93.46,"[[1.4, 12.3], [15.5, 30.6], [30.6, 38.7], [48....","[A man walked into the house, Another tall man..."
Shoplifting040_x264,907.05,"[[1.3, 16.5], [19.4, 27.0], [24.4, 29.0], [25....","[In a shopping mall, a bunch of people are buy..."
Shoplifting041_x264,411.30,"[[1.5, 5.8], [6.4, 18.6], [19.8, 35.8], [37.6,...",[A woman walked into the house and put her thi...
Shoplifting042_x264,170.75,"[[0.7, 4.6], [4.7, 9.6], [8.0, 9.0], [10.0, 18...",[A woman wearing sunglasses on her head pointe...
Shoplifting044_x264,485.17,"[[0.2, 32.3], [32.6, 46.6], [46.6, 64.8], [64....",[A man looked around at the door of the house ...
Shoplifting045_x264,54.73,"[[1.3, 8.3], [8.6, 14.3], [14.3, 18.2], [18.3,...",[A man in a red shirt and sunglasses entered t...
Shoplifting047_x264,79.29,"[[0.6, 12.1], [12.1, 22.5], [22.5, 31.3], [31....",[ Five women entered the supermarket one after...
Shoplifting048_x264,103.69,"[[1.8, 11.4], [11.4, 16.2], [16.2, 25.4], [25....",[The woman in red clothes picked up a pile of ...
Shoplifting049_x264,71.67,"[[5.6, 7.3], [7.3, 10.3], [10.3, 19.2], [10.9,...",[A man in green clothes walked out of the mobi...
Shoplifting050_x264,83.63,"[[2.7, 16.0], [16.4, 33.3], [33.7, 49.1], [49....",[ Six people gathered around a glass counter a...
Shoplifting051_x264,240.64,"[[15.6, 33.6], [35.7, 46.7], [46.7, 72.4], [72...","[A man wearing a white hat entered the house, ..."
Shoplifting052_x264,254.88,"[[6.5, 25.6], [26.4, 30.6], [31.5, 34.8], [35....",[A European-American man wearing a yellow shir...
Shoplifting053_x264,69.94,"[[1.8, 11.1], [12.6, 24.6], [24.6, 42.3], [42....",[A woman is holding a box of jewelry in her ha...
Shoplifting054_x264,34.23,"[[0.0, 16.8], [16.8, 34.2]]",[A man in a coat is lying on the mobile phone ...
Shoplifting055_x264,225.70,"[[6.8, 31.4], [31.4, 53.0], [58.0, 70.9], [70....",[Two women walked to the wine area of the supe...

,duration,timestamps,sentences
video_id,,,
Stealing002_x264,117.23,"[[8.6, 21.0], [24.2, 26.2], [26.2, 29.2], [28....",[A white car drove into the alley and stopped ...
Stealing003_x264,119.20,"[[0.0, 4.6], [4.6, 11.4], [5.0, 8.1], [55.1, 6...",[A man in black walked into a parking lot with...
Stealing004_x264,221.80,"[[0.0, 7.6], [7.6, 11.7], [12.2, 17.2], [20.1,...","[A man wearing black shoes, gray pants, gray s..."
Stealing006_x264,107.43,"[[0.0, 17.2], [25.2, 27.9], [27.9, 33.2], [33....",[There are many cars and motorcycles traveling...
Stealing007_x264,103.00,"[[0.0, 20.1], [20.1, 43.3], [39.5, 43.3], [44....",[There are many vehicles passing by on the roa...
Stealing008_x264,167.00,"[[0.0, 8.0], [10.1, 17.8], [17.8, 37.4], [37.4...",[A white truck drove on the road outside a rel...
Stealing009_x264,53.80,"[[0.0, 10.9], [10.9, 19.2], [19.2, 32.7], [40....",[A man in black walked from the road to a blac...
Stealing010_x264,101.10,"[[0.0, 9.8], [10.8, 19.8], [17.0, 19.8], [21.3...",[Many vehicles are driving on the road and man...
Stealing011_x264,123.90,"[[0.0, 7.2], [7.2, 20.2], [20.2, 36.6], [36.6,...",[A man in blue pants and a green shirt walked ...
Stealing012_x264,90.43,"[[9.5, 19.2], [19.2, 30.5], [30.5, 43.4], [43....",[A bald man with white clothes tied around his...
Stealing013_x264,308.37,"[[5.6, 9.0], [9.0, 15.4], [15.4, 25.5], [25.5,...",[A man wearing a white helmet and a man in bla...
Stealing014_x264,112.17,"[[0.0, 12.1], [12.1, 21.1], [21.1, 33.1], [33....",[A man in black standing at the door of the ya...
Stealing015_x264,60.00,"[[0.0, 8.9], [8.9, 22.4], [22.4, 32.2], [32.2,...","[A man wearing a blue down jacket, white pants..."
Stealing016_x264,81.67,"[[3.9, 24.6], [33.4, 43.3], [43.3, 59.2], [69....","[A man wearing gray clothes, blue pants and a ..."
Stealing017_x264,62.90,"[[0.0, 9.2], [7.0, 9.2], [9.2, 10.3], [11.2, 1...",[A bald man in green clothes hugged a woman in...
Stealing018_x264,68.40,"[[2.8, 9.3], [9.3, 18.8], [18.8, 27.8], [27.8,...",[A man in a plaid shirt ran to a black jeep pa...
Stealing019_x264,163.76,"[[6.9, 17.3], [17.3, 33.9], [33.9, 47.3], [47....","[A man wearing yellow pants, a dark gray top a..."
Stealing020_x264,220.13,"[[4.2, 16.1], [46.4, 50.1], [50.1, 55.5], [56....",[A car drove in from the alley and stopped nex...
Stealing021_x264,137.37,"[[0.0, 11.8], [11.8, 59.7], [59.7, 70.0], [70....","[A man wearing a gray hat, gray short sleeves,..."
Stealing022_x264,82.06,"[[0.0, 6.0], [6.0, 15.2], [15.2, 19.4], [21.8,...",[A woman with long black hair holds a piece of...
Stealing023_x264,169.17,"[[11.4, 27.6], [27.6, 39.0], [43.4, 60.9], [69...",[A black car slowly drove from the road onto t...
Stealing024_x264,82.20,"[[0.0, 7.2], [1.2, 3.2], [7.2, 18.0], [18.0, 2...",[There are seven tables of people eating in a ...
Stealing025_x264,727.24,"[[0.0, 10.0], [10.0, 23.4], [23.4, 38.8], [38....",[There are many vehicles driving on the road a...
Stealing026_x264,91.86,"[[35.6, 46.1], [46.1, 60.6], [60.6, 73.4], [73...",[A person with his face completely covered too...
Stealing027_x264,63.50,"[[2.2, 10.2], [10.2, 19.4], [19.4, 31.0], [31....",[Two men in black walked into a car. A man in ...
Stealing028_x264,59.21,"[[0.0, 6.2], [6.2, 16.0], [16.0, 25.6], [25.5,...","[A blue car passed by, A black car parked next..."
Stealing029_x264,13.58,"[[0.0, 2.1], [2.1, 5.1], [5.3, 11.8]]","[A black car drove to the door of a store, A m..."
Stealing030_x264,28.32,"[[3.0, 7.8], [9.9, 15.2], [15.2, 17.5], [18.2,...","[Two men in hats approached a car, Two men in ..."
Stealing031_x264,36.27,"[[0.0, 8.1], [8.1, 19.9], [19.9, 28.9], [28.9,...",[A man in black walked to the door of a house ...
Stealing032_x264,179.83,"[[0.0, 10.9], [0.0, 26.7], [33.3, 41.8], [43.0...","[Many people were eating in the restaurant, an..."
Stealing035_x264,371.85,"[[29.2, 38.5], [38.5, 47.6], [164.2, 168.4], [...",[Two men in black approached both sides of a b...
Stealing036_x264,84.39,"[[7.1, 18.3], [14.1, 18.3], [23.4, 44.2], [44....",[A man wearing striped clothes and a helmet ro...
Stealing037_x264,158.30,"[[0.0, 6.3], [6.3, 19.8], [19.8, 26.9], [26.9,...",[A man wearing a gray hat sticks his head out ...
Stealing042_x264,140.09,"[[0.0, 9.9], [9.9, 21.4], [32.3, 35.3], [38.3,...",[A man in green with a cloth on his shoulders ...
Stealing043_x264,160.47,"[[0.0, 7.0], [7.0, 14.8], [14.8, 25.0], [25.0,...",[Two men in hats walked to two black cars side...
Stealing044_x264,107.07,"[[0.0, 34.3], [38.0, 42.2], [54.2, 64.8], [64....","[Two people wearing peaked caps, a man and a w..."
Stealing045_x264,355.40,"[[0.0, 97.2], [106.2, 127.5], [127.5, 309.2]]",[A man came from a distance and wandered near ...
Stealing046_x264,343.60,"[[0.0, 12.5], [12.5, 35.5], [202.3, 212.1], [2...",[A man is trying to open the passenger door of...
Stealing047_x264,45.12,"[[0.0, 12.1], [16.2, 24.3], [24.3, 30.6]]",[A man in white clothes walked past a white ca...
Stealing048_x264,252.27,"[[0.0, 19.3], [28.1, 34.3], [34.3, 45.2], [77....","[Three motorcycles passed by on the road, A mo..."
Stealing049_x264,49.23,"[[0.0, 20.5], [20.5, 49.0]]","[A man wearing a white shirt, black trousers a..."
Stealing050_x264,111.63,"[[8.3, 21.0], [21.0, 84.3], [84.3, 90.0]]",[A man rode a bicycle to a black car and opene...
Stealing051_x264,111.04,"[[15.0, 22.2], [22.2, 35.0], [40.2, 42.2], [47...",[A white car drove up the road and stopped nex...
Stealing052_x264,112.58,"[[0.0, 30.5], [30.5, 100.5], [30.5, 100.5], [1...",[ When two men in black were passing by the pa...
Stealing053_x264,435.26,"[[0.0, 9.2], [9.2, 23.0], [23.0, 43.1], [43.1,...",[A man approached a white car and squatted dow...
Stealing054_x264,88.98,"[[0.0, 10.2], [17.0, 45.0], [48.5, 62.0], [59....","[A car came and stopped at the gas station, Th..."
Stealing055_x264,54.05,"[[0.0, 3.2], [3.2, 6.1], [6.2, 17.1], [19.2, 5...",[ A woman in black and a woman in white are co...
Stealing057_x264,100.62,"[[7.2, 14.0], [15.1, 20.1], [28.5, 33.6], [40....",[A woman in a skirt dragging her suitcase sat ...
Stealing058_x264,166.39,"[[7.0, 11.2], [11.2, 19.0], [55.2, 79.0], [118...",[A masked man picked the lock in front of the ...
Stealing059_x264,74.52,"[[3.0, 20.1], [20.1, 30.3], [37.3, 44.0], [60....",[A white car drove past a man in brown clothes...

,duration,timestamps,sentences
video_id,,,
Vandalism001_x264,47.80,"[[0.0, 1.9], [15.9, 23.5], [23.7, 35.3], [35.8...",[A man in black wearing a hat walked by with a...
Vandalism002_x264,61.39,"[[0.0, 4.2], [4.2, 13.2], [13.2, 16.5], [16.5,...",[A man in gray wearing a hat and carrying a bl...
Vandalism003_x264,49.10,"[[11.3, 12.5], [12.5, 16.0], [15.4, 19.6], [19...",[Two people running on the sidewalk. The perso...
Vandalism004_x264,94.00,"[[4.4, 6.5], [6.5, 11.4], [11.4, 28.5], [28.5,...",[A black car hit the fence around the traffic ...
Vandalism005_x264,54.21,"[[18.4, 21.8], [21.8, 25.9], [26.3, 28.7], [28...",[A man in gray clothes and a hat walked to a b...
Vandalism006_x264,27.09,"[[0.0, 10.3], [10.3, 18.1], [18.1, 23.2], [23....",[A man in a white shirt and black shorts hit a...
Vandalism007_x264,38.24,"[[0.0, 2.9], [0.0, 2.9], [2.9, 8.4], [8.4, 11....",[A man wearing a hat and carrying a black bag ...
Vandalism008_x264,419.73,"[[0.0, 9.6], [9.6, 20.0], [20.0, 30.3], [30.3,...","[A man in blue clothes, gray pants and black s..."
Vandalism009_x264,44.41,"[[10.8, 16.0], [16.0, 19.3], [19.9, 27.7], [27...",[A shirtless man wearing jeans walked to the m...
Vandalism010_x264,131.56,"[[11.5, 13.8], [13.8, 20.6], [20.6, 23.7], [23...",[A bearded cashier wearing a black shirt took ...
Vandalism011_x264,415.00,"[[27.0, 32.3], [32.3, 41.5], [41.5, 47.3], [47...",[Three people were walking on the street. One ...
Vandalism012_x264,28.19,"[[0.0, 5.7], [5.7, 10.2], [10.4, 13.0], [13.0,...","[Two men in black running on the street, A man..."
Vandalism013_x264,79.32,"[[0.0, 4.5], [4.5, 9.6], [14.7, 23.8], [23.8, ...","[A man in a gray shirt, a yellow shirt and a b..."
Vandalism014_x264,14.35,"[[0.0, 5.2], [6.6, 9.8]]",[A man wearing a gray coat and shirt pushed do...
Vandalism015_x264,99.40,"[[0.0, 5.8], [5.8, 14.7], [25.8, 31.1], [31.1,...",[A man in black clothes and a black hat walked...
Vandalism016_x264,193.73,"[[0.0, 16.9], [16.9, 33.8], [33.8, 47.4], [47....","[Two cars passing by each other, A white car b..."
Vandalism017_x264,33.82,"[[0.0, 4.7], [4.7, 6.1], [7.8, 11.7], [11.7, 1...","[A man wearing black pants with white spots, a..."
Vandalism018_x264,185.27,"[[0.0, 10.3], [10.3, 54.2], [54.2, 94.9], [94....",[A man in white walked into the store from the...
Vandalism019_x264,68.62,"[[0.0, 9.3], [21.4, 37.6], [37.6, 42.7], [45.4...",[A man in black carrying a bag with red patter...
Vandalism020_x264,48.28,"[[9.1, 10.7], [10.1, 17.0], [17.0, 22.0], [22....","[A car passed by on the road, A man wearing a ..."
Vandalism021_x264,45.52,"[[0.0, 6.0], [6.0, 11.1], [11.1, 32.6], [32.6,...","[A man wearing a hat, a white scarf, black clo..."
Vandalism022_x264,131.12,"[[3.4, 9.7], [9.7, 14.5], [14.5, 22.9], [22.9,...","[A man in white clothes, black trousers and a ..."
Vandalism023_x264,210.07,"[[0.7, 26.0], [26.0, 36.4], [36.4, 47.0], [170...","[At the end of the road, a person crosses the ..."
Vandalism024_x264,33.51,"[[11.2, 14.1], [16.5, 24.1], [24.1, 30.3]]","[A white car passed by, A bald man wearing a g..."
Vandalism025_x264,143.50,"[[0.0, 10.3], [10.3, 20.3], [20.3, 30.5], [30....",[A man wearing a blue hat and blue overalls wi...
Vandalism026_x264,32.43,"[[9.3, 17.9], [17.9, 27.6]]",[A man wearing a black hat and blue clothes an...
Vandalism027_x264,23.41,"[[5.8, 15.3], [15.3, 18.6]]",[A man in gray clothes and a black helmet walk...
Vandalism028_x264,149.94,"[[53.5, 61.3], [61.3, 68.2], [68.2, 80.5], [80...",[A man in clothes and hat walked to the front ...
Vandalism029_x264,15.23,"[[0.0, 7.2], [7.2, 10.5]]","[A man wearing yellow clothes, black pants, bl..."
Vandalism030_x264,48.04,"[[0.0, 9.0], [9.0, 16.2], [16.2, 25.0], [25.0,...",[Two people wearing down jackets ran from the ...
Vandalism031_x264,60.00,"[[9.7, 16.8], [9.7, 17.8], [16.8, 17.8], [17.8...",[A curly-haired man is throwing things into a ...
Vandalism032_x264,22.80,"[[0.0, 0.7], [5.1, 7.2], [7.2, 12.2]]","[There is a car passing by on the road, A man ..."
Vandalism033_x264,75.56,"[[0.0, 7.3], [10.9, 18.9], [15.9, 28.0], [18.9...",[Two men in black jumped on the outside of the...
Vandalism034_x264,58.56,"[[18.3, 22.1], [22.1, 30.1], [30.1, 32.1], [32...","[A man in blue pants, gray shirt, gray hat and..."
Vandalism035_x264,39.71,"[[0.0, 9.9], [3.0, 4.9], [3.0, 9.9], [9.9, 17....",[A man in gray clothes and a gray hat and a ma...
Vandalism036_x264,48.12,"[[0.0, 8.6], [14.3, 18.2], [18.2, 25.2], [24.2...","[A naked man walked into the store, walked to ..."
Vandalism038_x264,94.24,"[[0.0, 5.1], [5.1, 10.1], [10.1, 20.9], [20.9,...",[A man in gray clothes rode a bicycle from the...
Vandalism039_x264,30.02,"[[0.0, 8.8], [4.0, 8.8], [8.8, 14.6], [14.6, 2...","[Three cars passed by on the road,, Four peopl..."
Vandalism040_x264,34.60,"[[0.0, 4.2], [0.0, 4.2], [4.2, 14.9], [6.2, 14...",[A man in black without a hat pointed a wateri...
Vandalism041_x264,162.31,"[[0.0, 15.0], [15.0, 32.4], [32.4, 51.6], [51....",[ Seven people were walking on the street. A w...
Vandalism042_x264,119.92,"[[0.0, 17.0], [17.0, 34.3], [19.0, 34.3], [34....","[A group of six people are walking forward, an..."
Vandalism043_x264,108.16,"[[0.0, 5.9], [5.0, 5.9], [5.9, 8.9], [8.9, 10....",[A woman with red hair and a white skirt watch...
Vandalism044_x264,153.55,"[[4.9, 9.0], [10.0, 17.8], [17.8, 36.1], [36.1...",[A man in gray clothes and a hat threw the whi...
Vandalism045_x264,145.30,"[[0.0, 11.0], [11.0, 22.8], [22.8, 34.0], [34....",[A man in black walked from the road to a pill...
Vandalism046_x264,70.03,"[[0.0, 11.5], [11.5, 19.4], [19.4, 28.7], [28....",[A motorcycle slowly stopped on the road and l...
Vandalism047_x264,82.83,"[[1.9, 8.0], [8.0, 27.6], [27.6, 35.2], [35.2,...",[A man in black clothes and a blue hat punched...
Vandalism048_x264,239.49,"[[11.6, 14.9], [20.3, 24.8], [50.1, 58.0], [59...","[A motorcycle passed by on the road, A motorcy..."
Vandalism049_x264,266.68,"[[0.0, 6.5], [6.5, 14.9], [14.9, 27.3], [14.9,...",[A man wearing a black mask ran across the sid...
Vandalism050_x264,30.03,"[[0.0, 8.0], [8.0, 18.5], [18.5, 30.0]]",[There are three people next to a black car an...

In [ ]:
# SentrytNet - SlowFastR50 feeding into LSTM (Maybe with attention)

In [3]:
# Create datasets

In [4]:
# Train the dataset

In [ ]:
# Bleu score